.github/workflows/test-workflow.yml, alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/MonitorRunner.kt, build-tools/repositories.gradle, build.gradle, core/build.gradle, gradle.properties, notification/build.gradle
N/A
* Update test workflow to execute unit tests successfully
* Disable integ tests in the Test Workflow until they can be executed correctly
*CheckList:*
=> FIx Test Workflow

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, build.gradle, core/build.gradle, notification/build.gradle
N/A
* Fix integ tests so they execute successfully in the test workflow
*CheckList:*
=> Fix integ tests so they execute successfully in the test workflow

alerting/build.gradle, alerting/src/test/kotlin/com/amazon/opendistroforelasticsearch/alerting/resthandler/MonitorRestApiIT.kt, build-tools/pkgbuild.gradle, build.gradle
N/A
Update plugin install name and add beta1 to version
*CheckList:*
=> Update plugin install name

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, build.gradle, release-notes/opensearch-index-management.release-notes-1.0.0.0-beta1.md
N/A
* Update version to 1.0.0.0-beta1
*CheckList:*
=> Update version to 1.0.0.0-beta1

.github/draft-release-notes-config.yml, release-notes/opensearch-alerting.release-notes-1.0.0.0-rc1.md
N/A
* Add rc1 release notes
*CheckList:*
=> Add rc1 release notes

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml
=> Updating the Open-search Branch to 1.0

build.gradle
*Issue #, if available:* 
*Description of changes:* Adding Ktlint formatting check to the Gradle build task.
*CheckList:*
=> Adding Ktlint formatting check to the Gradle build task.

alerting/src/main/kotlin/org/opensearch/alerting/settings/LegacyOpenDistroDestinationSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/settings/DestinationSettingsTests.kt
*Description of changes:* Updating UTs for the Destination Settings
*CheckList:*
=> Updating UTs for the Destination Settings

alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/AlertingUtilsTests.kt
*Issue #, if available:* 
*Description of changes:* Adding additional null checks for the URLs not present for the case of SNS as a destination message. 
*CheckList:*
=> Adding additional null checks for URL not present.

alerting/build.gradle
N/A
Enable license headers check
*CheckList:*
=> Wnable license headers check

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, build.gradle
Signed-off-by: Thomas Hurney hurneyt@amazon.com
N/A
Updated OpenSearch versions from 1.0.0.0-rc1 to 1.0.0.0.
*CheckList:*
=> Updated OpenSearch versions from 1.0.0.0-rc1 to 1.0.0.0.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
N/A
Remove default assignee
*CheckList:*
=> Remove default assignee

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
*Issue #, if available:* #129 
This commit addresses the usages of the actionGet API calls which are blocking in nature and block the execution of the program. This is replaced by the callback listeners for the API call response. 
*CheckList:*
=> Removing All Usages of Action Get Method Calls and adding the listeners

release-notes/opensearch-alerting.release-notes-1.1.0.0.md
Adds release notes for 1.1.0.0 release
*CheckList:*
=> Add release notes for 1.1.0.0 release

README.md, alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
=> Cherry-pick commits to 1.x

.github/workflows/dco.yml, NOTICE.txt, release-notes/opensearch-alerting.release-notes-1.2.0.0.md
Signed-off-by: Annie Lee <leeyun@amazon.com>
Cherry-picking commit 3a35bb612e9c078a05505e2f9231958a5719193a
*CheckList:*
=> Update release note and copy right notice, and add dco workflow

.github/workflows/dco.yml, NOTICE.txt, release-notes/opensearch-alerting.release-notes-1.2.0.0.md
Signed-off-by: Annie Lee <leeyun@amazon.com>
Cherry-picking commit 3a35bb612e9c078a05505e2f9231958a5719193a
*CheckList:*
=> Update release note and copy right notice, and add dco workflow 

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle, build.gradle
Bump version to 1.2.1.0
*CheckList:*
=> Bump version to 1.2.1.0

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle, build.gradle
N/A
Bumping Alerting to 1.2.2.0.
*CheckList:*
=> Update version to 1.2.2.0

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle, build.gradle
Coming from https://github.com/opensearch-project/opensearch-build/issues/1417.
=> Incremented version to 1.2.4.

alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, build.gradle, core/build.gradle
* Update cron-utils
N/A
Backport updating cron-utils
*CheckList:*
=> Update cron-utils (#266)

alerting/src/main/kotlin/org/opensearch/alerting/model/AlertingConfigAccessor.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
N/A
- Add update monitor function. This will be used to update the monitor's last run context info in doc level monitor
*CheckList:*
=> Add update monitor function

release-notes/opensearch-alerting.release-notes-1.2.4.0.md
N/A
- Add 1.2.4.0 release notes
*CheckList:*
=> Add 1.2.4.0 release notes

.github/workflows/bwc-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml
Updating GitHub Action workflows to be consistent on all branches since the changes made under `main` isn't being reflected in old branches because they have a different definition of the workflows under `.github`
*CheckList:*
=> Update GitHub Actions workflows to be consistent across branches

alerting/src/test/kotlin/org/opensearch/alerting/ADTestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/DestinationTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
*Issue #, if available:* https://github.com/opensearch-project/alerting/issues/219
*Description of changes:* Adding Constants in place of hard coded variables. 
*CheckList:*
=> Addition of Constants 

alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
*Issue #, if available:* https://github.com/opensearch-project/alerting/issues/219
*Description of changes:* Integration Tests for New Roles created with limited Permissions
*CheckList:*
Tests Passing Locally: https://github.com/aditjind/alerting/pull/1  
=> Integration Tests for New Roles created with limited Permissions

alerting/src/test/kotlin/org/opensearch/alerting/ADTestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/DestinationTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Merging commits `36c6edd946b5a9713a56f7c436429cbf8d6c0336` to `92aa4bda9d2c42342f3e5bf9b28c54d96be8ec44` (inclusive) from `main` to `1.x` to maintain parity.
*CheckList:*
=> Merge main to 1.x

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Fixes some failing security tests that were added as part of #287
*CheckList:*
=> Fix security tests with partial permissions in 1.x

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Fixes some failing security tests that were added as part of #284
*CheckList:*
=> Fix security tests with partial permissions in 1.2

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Fixes some failing security tests that were added as part of #285
*CheckList:*
=> Fix security tests with partial permissions in 1.1

build-tools/repositories.gradle, build.gradle
Signed-off-by: jiahe zhang <zhanncha@amazon.com>
https://github.com/opensearch-project/alerting/issues/278
*CheckList:*
=> jcenter dependencies removed

release-notes/opensearch-alerting.release-notes-1.3.0.0.md
https://github.com/opensearch-project/alerting/issues/314
Adding release notes for 1.3.
*CheckList:*
=> Added 1.3 release notes.

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle, build.gradle
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.
=> Incremented version to 1.3.2.

docs/document-level-alerting-rfc.md
#238
- Add RFC document for Document Level Alerting
*CheckList:*
=> Add Document Level Alerting RFC

alerting/build.gradle, build.gradle
Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.
=> Change 2.0-alpha1 to 2.0-rc1.

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/action/node/ScheduledJobsStatsResponse.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInput.kt, core/src/main/resources/mappings/doc-level-queries.json
- Remove the usage of actionGet to remove blocking calls
- Fix minor bugs for document level alerting
*CheckList:*
=> Remove actionGet and fix minor bugs

release-notes/opensearch-alerting.release-notes-2.0.0.0-rc1.md
N/A
- Add release notes for version 2.0.0-rc1
*CheckList:*
=> Add release notes for version 2.0.0-rc1

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/action/node/ScheduledJobsStatsResponse.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInput.kt, core/src/main/resources/mappings/doc-level-queries.json, release-notes/opensearch-alerting.release-notes-2.0.0.0-rc1.md
N/A
* Backport bug fixes, action get removal, and release notes
*CheckList:*
=> Backport bug fixes, action get removal, and release notes

alerting/src/main/kotlin/org/opensearch/alerting/action/GetFindingsAction.kt, release-notes/opensearch-alerting.release-notes-2.0.0.0-rc1.md
N/A
* Fix Finding action naming and update release notes
*CheckList:*
=> Fix Finding action naming and update release notes

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Alert.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/AlertingConfigAccessor.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTriggerRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/MonitorMetadata.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/action/ActionExecutionPolicy.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/ADTestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorResponseTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/IndexMonitorResponseTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/DocLevelMonitorInputTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/WriteableTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/XContentTests.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/DocLevelQuery.kt, core/src/main/resources/mappings/scheduled-jobs.json
N/A
- Fix minor bugs
- Validate query name or tags for DocLeveQueries
- Fix Document Level monitor wildcard index support
- Support per alert action execution for Document Level Monitors
- Creates a new metadata document to help support future throttling use cases and robustness of Document Level Monitors
*CheckList:*
=> Fix minor bugs and support per alert action execution for Document Level Monitors

alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
N/A
- Fix elevated security permission with Notification that sends notification even when user has no permissions with Notification
- Fix validating indexing document level monitor with user with limited permissions
- Increase Document Level Monitor dry run search depth
*CheckList:*
=> Fix elevated security permission with Notification and minor bug fixes

alerting/build.gradle, build.gradle
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
*CheckList:*
=> Incremented version to 2.0.1

alerting/build.gradle, build.gradle
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Cherry-picked `2.0.1` bump commit.
*CheckList:*
=> Cherry-picked 2.0.1 bump commit.

release-notes/opensearch-alerting.release-notes-2.1.0.0.md
https://github.com/opensearch-project/alerting/issues/473
Added 2.1 release notes.
*CheckList:*
=> Added 2.1 release notes.

alerting/build.gradle, build.gradle
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
Increment to 1.3.4
*CheckList:*
=> Incremented version to 1.3.4.

alerting/build.gradle, alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt
=> Backporting commit to feature dev branch

alerting/build.gradle, alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt
=> Backporting commits to development branch.

alerting/build.gradle, build.gradle, release-notes/opensearch-alerting.release-notes-2.2.0.0.md
Cherry-picked 2.2 commits to main.
*CheckList:*
=> Cherry-picked 2.2 commits to main.

release-notes/opensearch-alerting.release-notes-2.3.0.0.md
https://github.com/opensearch-project/alerting/issues/534
Added 2.3 release notes.
*CheckList:*
=> Added 2.3 release notes.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt
Recreate request object from writeable for Get alerts and get findings
=> Recreate request object from writeable for Get alerts and get findings

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
=> support query deletion from custom query index on delete monitor

release-notes/opensearch-alerting.release-notes-1.3.6.0.md
Add 1.3.6 release notes
*CheckList:*
=> Add 1.3.6 release notes

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
This PR backports #591 from main to 2.x
=> Use custom query index in update monitor flow (#591)

alerting/build.gradle
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/alerting/issues/533
Added groupId as org.opensearch.plugin in pluginZip publication
*CheckList:*
=> Added groupId as org.opensearch.plugin in pluginZip publication

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
=> Support fetching alerts by list of alert ids in Get Alerts Action

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
fixed searchAlerts to search alertIndex from monitor dataSources instead of original hardcoded index
*CheckList:*
=> fixed searchAlerts to search alertIndex from monitor dataSources

.github/workflows/test-workflow.yml, alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt, scripts/build.sh
fix for windows ktlint issue
#573 
#570 
fix for windows ktlint issue. tested this on windows server 2022 on ec2.
*CheckList:*
=> fix for windows ktlint issue

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
*Issue #, if available:* 586
Refactored DeleteMonitor Action to be synchronious
*CheckList:*
=> refactored DeleteMonitor Action to be synchronious

.github/workflows/test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertMover.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt, scripts/build.sh
2.4 backport from 2.x
*CheckList:*
=> 2.4 backport from 2.x

alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
=> add tests to verify owner field in Monitor

release-notes/opensearch-alerting.release-notes-2.4.0.0.md
Updates release notes with #636 
*CheckList:*
=> update release notes

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt, build.gradle
create findingIndex bugfix
*CheckList:*
=> create findingIndex bugfix

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
=> set lastnotification time as created time for new bucket level monitor

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
=> Mappings fix backport 2.x

release-notes/opensearch-alerting.release-notes-2.5.0.0.md
https://github.com/opensearch-project/alerting/issues/732
Added 2.5 release notes.
*CheckList:*
=> Added 2.5 release notes.

DEVELOPER_GUIDE.md, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
#756
Dev guide update to include building/using local os-min distro
*CheckList:*
=> Dev guide update to include building/using local os-min distro

.github/workflows/maven-publish.yml, alerting/build.gradle
#802
Publish snapshots to maven via GHA
*Testing:*
```
find alerting/snapshots | sort
alerting/snapshots
alerting/snapshots/org
alerting/snapshots/org/opensearch
alerting/snapshots/org/opensearch/plugin
alerting/snapshots/org/opensearch/plugin/alerting
alerting/snapshots/org/opensearch/plugin/alerting/3.0.0.0-SNAPSHOT
alerting/snapshots/org/opensearch/plugin/alerting/3.0.0.0-SNAPSHOT/alerting-3.0.0.0-20230221.175611-1.pom
alerting/snapshots/org/opensearch/plugin/alerting/3.0.0.0-SNAPSHOT/alerting-3.0.0.0-20230221.175611-1.pom.md5
alerting/snapshots/org/opensearch/plugin/alerting/3.0.0.0-SNAPSHOT/alerting-3.0.0.0-20230221.175611-1.pom.sha1
alerting/snapshots/org/opensearch/plugin/alerting/3.0.0.0-SNAPSHOT/alerting-3.0.0.0-20230221.175611-1. …
```
=> Publish snapshots to maven via GHA

core/src/main/resources/mappings/scheduled-jobs.json
revert https://github.com/opensearch-project/alerting/pull/804
*CheckList:*
=> revert enabled field in source_to_query_index_mapping

build.gradle
N/A
Increment version to 2.7
*CheckList:*
=> Increment version to 2.7

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
#844
backport from main
*CheckList:*
=> Doc transform 2.x backport

.github/CODEOWNERS, MAINTAINERS.md
#793
Baseline codeowners and maintainers
*CheckList:*
=> Baseline codeowners and maintainers

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
*Issue #, if available:* #817
*CheckList:*
=> DocLevelMonitor Error Alert revisit

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
=> Backport 905 to 2.7

.github/CODEOWNERS
=> Updating the CODEOWNERS file with the right format

alerting/build.gradle, build.gradle
#917
Correctly retrieve 1.3.10 common-utils artifact and fix package conflicts
*CheckList:*
=> Fix 1.3.10 build issues

release-notes/opensearch-alerting.release-notes-1.3.10.0.md
Added 1.3.10 release notes.
*CheckList:*
=> Added 1.3.10 release notes.

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Chime.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/CustomWebhook.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Slack.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/email/EmailGroup.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingException.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AnomalyDetectionUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationConversionUtils.kt, core/src/main/kotlin/org/opensearch/alerting/core/resthandler/RestScheduledJobStatsHandler.kt
Fixed Strings class import due to core's recent change where this class was moved to another package
*CheckList:*
=> Compile fix - Strings package change

release-notes/opensearch-alerting.release-notes-2.8.0.0.md
=> Added 2.8 release notes

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json
add workflow_id field in alert mapping json
=> add workflow_id field in alert mapping json

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Chime.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/CustomWebhook.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Slack.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/email/EmailGroup.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingException.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AnomalyDetectionUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/RestHandlerUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationConversionUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationUtilService.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt, core/src/main/kotlin/org/opensearch/alerting/core/resthandler/RestScheduledJobStatsHandler.kt
N/A
Resolve string issues from core to allow the plugin to compile
*CheckList:*
=> Resolve string issues from core

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
#996 
Backport of #991 
*CheckList:*
=> [Backport 2.x] Fix getAlerts RBAC problem (#991)

release-notes/opensearch-alerting.release-notes-2.9.0.0.md
https://github.com/opensearch-project/alerting/issues/972
Added 2.9 release notes.
*CheckList:*
=> Added 2.9 release notes.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
#996 
Backport of #991 
*CheckList:*
=> [Backport 2.5] Fix getAlerts RBAC problem (#991)

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
#996 
Backport of #991 
*CheckList:*
=> [Backport 2.6] Fix getAlerts RBAC problem (#991)

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/RestHandlerUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationUtilService.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt
update alerting main after core changes
*CheckList:*
=> update alerting main after core changes

.github/workflows/maven-publish.yml, alerting/build.gradle
N/A
Backport of #805 
*CheckList:*
=> [Backport 1.3] Publish snapshots to maven via GHA (#805)

.github/workflows/maven-publish.yml
N/A
Change version to jdk 11 for maven publish
*CheckList:*
=> Change version to jdk 11 for maven publish

release-notes/opensearch-alerting.release-notes-2.10.0.0.md
N/A
Added 2.10 release notes
*CheckList:*
=> Added 2.10 release notes

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
=> optimize doc-level monitor workflow for index patterns

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
=> fix workflow execution for first run

release-notes/opensearch-alerting.release-notes-2.11.0.0.md
https://github.com/opensearch-project/alerting/issues/1137
Drafted 2.11 release notes.
*CheckList:*
=> Drafted 2.11 release notes.

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml
=> [PR3]Ensure Github workflow runs on docker image used by Production Distribution Build alerting

alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
Add nested fields param mapping findings index for doc level queries
=> Add nested fields param mapping findings index for doc level queries

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
Backport #1240 and #1276 to 2.x
*CheckList:*
=> [Backport 2.x] Backport #1240 and #1276 to 2.x

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
Backport #1240 and #1276 to 2.11
*CheckList:*
=> [Backport 2.11] Backport #1240 and #1276 to 2.11

release-notes/opensearch-alerting.release-notes-2.11.1.0.md
Added 2.11.1 release notes.
*CheckList:*
=> Added 2.11.1 release notes.

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
This reverts commit c00c86d360b80b8e3b91795b799e2f5b7f590a3b.
*CheckList:*
=> Revert commit c00c86d360b80b8e3b91795b799e2f5b7f590a3b

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt
#1325 
Backport of 1325 to 2.11
*CheckList:*
=> Backport #1325 to 2.11

alerting/build.gradle
https://github.com/opensearch-project/alerting/issues/1358
https://github.com/advisories/GHSA-qphf-w3cq-jpmx - Medium Severity Vulnerability fixed in version 5.4.1
*CheckList:*
=> ipaddress lib upgrade as part of cve fix

scripts/build.sh
Add publishToMavenLocal in build.sh
*CheckList:*
=> Add publishToMavenLocal in build.sh

.github/CODEOWNERS, MAINTAINERS.md
Added @engechas as a maintainer.
*CheckList:*
=> Added engechas as a maintainer.

alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt
```
when the source_to_query_index_mapping field is upserted without the .opendistro-alerting-config index present, the mapping for it gets corrupted.
"source_to_query_index_mapping": {
"properties": {
"ocsf_api_activityXnRAfI0B9Qgmh2Pzq4q4": {
"type": "text",
"fields": {
"keyword": {
"type": "keyword",
"ignore_above": 256
}
}
}
}
}
```
the correct mapping for the field is,
```
"source_to_query_index_mapping": {
"type": "object",
"enabled": false
}
```
this pr ensures that the `upsert` doesn't happen if the index is not present.
*CheckList:*
For more information on following Developer Certificate of Origin and signing off …
=> fix for MapperException[the [enabled] parameter can't be updated for the object mapping [metadata.source_to_query_index_mapping]

alerting/build.gradle, build.gradle
1. Adjusted `com.github.seancfoley:ipaddress` version to address CVE.
2. Adjusted `ktlint` dependencies to address CVE.
*CheckList:*
=> Adjusted dependency versions to address CVEs.

release-notes/opensearch-alerting.release-notes-1.3.15.0.md
=> Add 1.3.15 release notes

.github/CODEOWNERS, MAINTAINERS.md
Added @jowg-amazon as a maintainer.
*CheckList:*
=> Add jowg-amazon to maintainers

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
*Issue #, if available:* https://github.com/opensearch-project/security-analytics/issues/718
Manually resolves backport of #1325 
*CheckList:*
=> Backport 1325 to 2.7

alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/AlertContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/BucketLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AggregationQueryRewriter.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/AlertContextTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/AlertingUtilsTests.kt
Manual backport of PR https://github.com/opensearch-project/alerting/pull/1450
*CheckList:*
=> [Backport 2.x] Enhance per bucket, and per document monitor notification message ctx. (#1450)

release-notes/opensearch-alerting.release-notes-2.13.0.0.md
*Add release notes for 2.13*
*CheckList:*
=> Add release notes 2.13

release-notes/opensearch-alerting.release-notes-2.14.0.0.md
https://github.com/opensearch-project/alerting/issues/1495
Added 2.14 release notes.
*CheckList:*
=> Added 2.14 release notes.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
changes to add start_time and end_time filters to getAlertsRequest
*CheckList:*
=> changes to add start_time and end_time filters to getAlertsRequest

release-notes/opensearch-alerting.release-notes-2.15.0.0.md
Add release notes for 2.15
*CheckList:*
=> Add 2.15 release notes

core/build.gradle
=> remove redundant dependencies

alerting/src/main/kotlin/org/opensearch/alerting/remote/monitors/RemoteDocumentLevelMonitorRunner.kt, sample-remote-monitor-plugin/src/test/java/org/opensearch/alerting/SampleRemoteMonitorIT.java
=> fix minor bug in remote monitor impl

.github/workflows/test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
=> fix minor bug in lock handler

alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
=> [Backport] Enable cross-cluster monitor cluster setting #1612

release-notes/opensearch-alerting.release-notes-2.16.0.0.md
*Added release notes for 2.16*
*CheckList:*
=> added release notes for alerting

alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Reverts opensearch-project/alerting#1618
=> Revert "[Backport 2.13] [Backport 2.x] Enable cross-cluster monitor cluster setting #1612"

alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Reverts opensearch-project/alerting#1615
=> Revert "[Backport 2.15] [Backport] Enable cross-cluster monitor cluster setting #1612"

.github/workflows/security-test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/lock/LockService.kt
manual backport of #1627 
*CheckList:*
=> [Backport 2.11] fix monitor renew lock issue (#1627)

.github/CODEOWNERS, MAINTAINERS.md
Added @amsiglan and @goyamegh as maintainers.
=> Added maintainers.

release-notes/opensearch-alerting.release-notes-2.17.0.0.md
=> Added 2.17 release notes

.github/workflows/test-workflow.yml
upgrade upload-artifact to v3 (#1656) (#1658) (#1677)
=> upgrade upload-artifact to v3 (#1656) (#1658) (#1677)

build.gradle
[Describe what this change achieves]
=> Increment version to 2.15.1-SNAPSHOT (#1586)

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
fix git merge issues introduced with #1671
=> fix git merge issues introduced with #1671

release-notes/opensearch-alerting.release-notes-2.18.0.0.md
Added 2.18.0 release notes.
https://github.com/opensearch-project/alerting/issues/1654
=> Added 2.18.0 release notes.

.github/workflows/auto-release.yml, .github/workflows/bwc-test-workflow.yml, .github/workflows/maven-publish.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml
Upgrades to actions/upload-artifact@v4 to resolve CI issues
Resolves https://github.com/opensearch-project/alerting/issues/1726
=> Upgrade to upload-artifact v4

.github/workflows/multi-node-test-workflow.yml
=> Fixed typo in CI workflow.

release-notes/opensearch-alerting.release-notes-2.19.0.0.md
Added 2.19 release notes.
https://github.com/opensearch-project/alerting/issues/1719
=> Added 2.19 release notes.

build.gradle
=> bump logback to 1.5.16 

release-notes/opensearch-alerting.release-notes-2.19.1.0.md
=> 2.19.1 release notes added

.github/workflows/security-test-workflow.yml, alerting/build.gradle, alerting/src/test/kotlin/org/opensearch/alerting/ODFERestTestCase.kt, build.gradle
1. Dynamically determine version for BWC tests.
1. Fix security test workflow.
https://github.com/opensearch-project/alerting/pull/1786#issuecomment-2686517166
=> Fix security-enabled test configurations for 3.0-alpha1.

release-notes/opensearch-alerting.release-notes-3.0.0.0-alpha1.md
Added 3.0.0-alpha1 release notes.
https://github.com/opensearch-project/alerting/issues/1035
=> Added 3.0.0-alpha1 release notes.

build.gradle
Update version qualifier to beta1.
https://github.com/opensearch-project/alerting/issues/1035
=> Update version qualifier to beta1.

release-notes/opensearch-alerting.release-notes-3.0.0.0-alpha1.mdopensearch-alerting.release-notes-3.0.0.0-beta1.md
Added 3.0-beta1 release notes.
https://github.com/opensearch-project/alerting/issues/1035
=> Added 3.0-beta1 release notes.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
The transport layer has a few api calls for CRUD operations which are callback based, examples are client.search(), client.index(), client.get() etc. These take an additional callback parameter, refactor them to run in a co-routine using client.suspendUntil() instead of using callback based paradigm.
=> Refactored callback based search api calls in TransportIndexMonitorAction

release-notes/opensearch-alerting.release-notes-2.19.3.0.md
=> Added 2.19.3.0 release notes
