THIRD-PARTY
This affects the package com.fasterxml.jackson.dataformat:jackson-dataformat-cbor from 0 and before 2.11.4, from 2.12.0-rc1 and before 2.12.1. Unchecked allocation of byte buffer can cause a java.lang.OutOfMemoryError exception.
=> Update jackson CVE-2020-28491

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestAcknowledgeAlertAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/DestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/EmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/EmailGroupRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/resthandler/RestScheduledJobStatsHandler.kt, notification/build.gradle
*Issue #, if available:* Resolves
*Description of changes:* REST APIs for ODFE are compatible in addition to the new API path. 
New API Path is `"/_plugins/_alerting/monitors"` and `"/_plugins/_alerting/destinations"`
*CheckList:*
Testing: 
Added UTs to check if the old path is still valid. 
=> Adding Rest APIs Backward Compatibility with ODFE

alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt
*Issue #, if available:* Current REST API calls are incompatible with security enabled clusters. Added a check for the current ITs to pass with the security disabled cluster. 
Other IT tests in our Framework use the SecureClientBuilder. [Here](https://github.com/opendistro-for-elasticsearch/alerting/blob/ea60c949dfd8f95088b92e40b40857650c4d0ce4/alerting/src/test/kotlin/com/amazon/opendistroforelasticsearch/alerting/resthandler/SecureMonitorRestApiIT.kt#L41) 
We need to implement the same client in our current ITs
*CheckList:* …
=> Adding check for security enabled

.github/workflows/multi-node-test-workflow.yml
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
*Description of changes:* Added the workflow to run the integration tests with security plugin installed on an Open-search cluster created via Docker Image for the staging artifacts. 
*CheckList:*
=> Adding Workflow to test the Security Integration tests with the Security Plugin Installed on Opensearch Docker Image

core/build.gradle
Upgrade google-java-format to 1.10.0 to pick guava v30
Upgrade google-java-format to 1.10.0 to pick guava v30
*CheckList:*
=> Upgrade google-java-format to 1.10.0 to pick guava v30

release-notes/opensearch-alerting.release-notes-1.0.0.0.md
Signed-off-by: Thomas Hurney [hurneyt@amazon.com](mailto:hurneyt@amazon.com)
N/A
Added release notes for OpenSearch-Alerting 1.0.0.0. These release notes include notes from OpenSearch-Alerting 1.0.0.0-rc1.
*CheckList:*
=> Added release notes for OpenSearch 1.0.0.0.

release-notes/opensearch-alerting.release-notes-1.0.0.0.md
=> Added release notes for OpenSearch 1.0.0.0 to main branch (#123)

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, .gitignore, alerting/build.gradle, build.gradle
Signed-off-by: dblock <dblock@amazon.com>
Fixes https://github.com/opensearch-project/alerting/issues/141 and defaults to building a `-SNAPSHOT` version.
Depends on https://github.com/opensearch-project/common-utils/pull/58/files
*CheckList:*
=> Fix snapshot build and increment to 1.1.0.

docs/bucket-level-alerting-rfc.md
Updating Bucket-Level Alerting RFC to reflect the feature name for posterity as well as updating the issue link to the OpenSearch Alerting equivalent.
*CheckList:*
=> Update Bucket-Level Alerting RFC

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregationBuilder.kt, alerting/src/main/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregator.kt, alerting/src/main/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtFilter.kt, alerting/src/main/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorIndices.kt, alerting/src/test/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregationBuilderTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregatorTests.kt
**BucketSelectorExt** is an extension to [BucketSelector](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-selector-aggregation.html) pipeline aggregation. Some of the limitations with BucketSelector - 
1. Only one bucket selector can be applied on a parent multi-bucket aggregation. Since, BucketSelector retains the selected buckets and discards the others, so allowing multiple BucketSelector for an aggregation isn't the ideal behavior.
2. Key filters are not supported. Script variables in BucketSelector only pertains to the numeric values and keys cannot be used a script variable to write selection expression. 
3. Doesn't works with …
=> Add BucketSelector pipeline aggregation extension

alerting/src/main/kotlin/org/opensearch/alerting/model/AggregationResultBucket.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
Add AggregationResultBucket class which will be used for the Bucket-Level Trigger run result data.
*CheckList:*
=> Add AggregationResultBucket

alerting/src/main/kotlin/org/opensearch/alerting/model/action/Action.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/action/ActionExecutionPolicy.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/action/ActionExecutionScope.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
Adds ActionExecutionPolicy which will be used for Action configuration in Bucket-Level Monitors.
*CheckList:*
=> Add ActionExecutionPolicy

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt
During a Bucket-Level Monitor execution, if we encounter exceptions at the Trigger level, we will skip categorization of Alerts for that Trigger but still execute the Actions (using `PER_EXECUTION` scope to avoid spam) so that `ctx.error` can be populated and propagate the issue to the user.
Also, in the case of a MonitorResult error (which is a Monitor-level failure) we will still enter the main triggers loop and run each Trigger (which will then fail since the search result probably failed). This is fine for now since it still leads to the categorization of Alerts under each Trigger being skipped and all actions for all Triggers being executed to notify the user. In the future, when …
=> Execute Actions on runTrigger exceptions for Bucket-Level Monitor

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt
Filter out Acknowledged Alerts when executing Actions for Bucket-Level Monitors
*CheckList:*
=> Skip execution of Actions on ACKNOWLEDGED Alerts for Bucket-Level Monitors

integtest.sh
* Add integtest script to the repo
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
* Add Alerting specific security param for integTest
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
N/A
Backport integtest.sh file for 1.0
*CheckList:*
=>  Add Integtest.sh for OpenSearch integtest setups (#121)

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt
When iterating over paginated aggregation results (composite aggregations) for Bucket-Level Monitors, the next page of MonitorRunResults are retrieved for each iteration while an `after_key` is present. Whether there are results or not, the final page (the one with `after_key == null`) is empty and since the final state of MonitorRunResult is what is returned by the MonitorRunner for Bucket-Level Monitor execution, it ends up returning an empty result even in the case where there was data which can be misleading. This fixes that bug by returning the first page of results in all cases so if there was data, it is at least reflected in the output.
*CheckList:*
[x] Commits are signed per the …
=> Return first page of input results in MonitorRunResult for Bucket-Level Monitor

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt
* Adds a setting for max actionable Alerts when using `PER_ALERT` Action execution scope for Bucket-Level Alerting, if this value is exceeded, the Action execution will fallback to `PER_EXECUTION` scope regardless of the Action configuration
* Adds check to skip saving Alerts for test Monitors (similar to what is already done in the Query-Level Monitor execution)
*CheckList:* …
=> Add setting to limit per alert action executions and don't save Alerts for test Bucket-Level Monitors

alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/MonitorRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AggregationQueryRewriter.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/AggregationQueryRewriterTests.kt
For Bucket-Level Monitors, different Triggers can potentially have different bucket paths that they are evaluating the conditions against. For paginated aggregation queries, different bucket paths could have different page counts meaning that they will completed independently as the data is being paginated. This change makes it so the after_key can be independently kept for each bucket path to handle the case where one bucket path completes pagination while the others still have data to be iterated through.
*CheckList:*
For …
=> Fix bug in paginating multiple bucket paths for Bucket-Level Monitor

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AggregationQueryRewriter.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
* Fixes bug where throttle response was not being properly reflected when running Action for `PER_ALERT` scope
* Fixes bug where COMPLETED Alerts were not being saved when all the Actions were of `PER_ALERT` scope with the default actionable categories of new and de-duped Alerts
* Fixes bug where rewriting query changes the input on the Monitor directly
*CheckList:* …
=> Various bug fixes for Bucket-Level Alerting

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Return only monitors for /monitors/_search.
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/61
*CheckList:*
=> Return only monitors for /monitors/_search.

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/action/Action.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/action/ActionExecutionPolicy.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/XContentTests.kt
Previously, since the `ActionExecutionScope` was required for Bucket-Level Monitor executions, the default configuration was being put into the Action config itself. The problem with this was that Action is Monitor agnostic so it is not aware of the Monitor type it is being defined for. This means that the Action policy default (which is meant for Bucket-Level Monitors) would have been put into every Action defined in Query-Level Monitor if none were explicitly given which could cause backwards compatibility issues if the `ActionExecutionPolicy` integrates with Query-Level Monitors in the future.
To clean up the `ActionExecutionPolicy` behavior, the following changes were made:
* …
=> Resolve default for ActionExecutionPolicy at runtime

release-notes/opensearch-alerting.release-notes-1.1.0.0.md
Backport commit to add release notes for 1.1.0.0 from `main` to `1.x`
*CheckList:*
=> Add release notes for 1.1.0.0 release

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, release-notes/opensearch-alerting.release-notes-1.1.0.0.md
Add valid search filters.
Add valid search filters.
*CheckList:*
=> Add valid search filters.

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, build-tools/repositories.gradle, build.gradle
Signed-off-by: Robert Downs <downsrob@amazon.com>
opensearch-project/opensearch-build#663
Updates alerting version to 1.2. Changes the gradle build file, as well as the github test and build workflows.
*CheckList:*
=> Updates alerting version to 1.2

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Signed-off-by: Thomas Hurney <hurneyt@amazon.com>
1. #203 
2. Alerting-Dashboard-Plugin [PR #126](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/126)
Porting fix implemented in PR #205.
*CheckList:*
=> Fixed a bug that was preventing the AcknowledgeAlerts API from acknowledging more than 10 alerts at once.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Signed-off-by: Thomas Hurney <hurneyt@amazon.com>
1. #203 
2. Alerting-Dashboard-Plugin [PR #126](https://github.com/opensearch-project/alerting-dashboards-plugin/issues/126)
Porting fix implemented in PR #205.
*CheckList:*
=> Fixed a bug that was preventing the AcknowledgeAlerts API from acknowledging more than 10 alerts at once

alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt, build.gradle
#139 
* Passed security integ tests using OpenSeach-1.1 release: `./gradlew :alerting:integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=opensearch -Dhttps=true -Dsecurity=true -Duser=admin -Dpassword=admin`. 
#139 
* Added changes that will ensure that `admin` users can access all monitors.
* Refactored the transport classes which have filter-by-backend-role logic.
* There is scope to improve security tests added a seperate issue #219 , as fast follow up to this.
*CheckList:*
For more information on following Developer …
=> Admin Users must be able to access all monitors #139

notification/build.gradle, scripts/build.sh
Signed-off-by: Marc Handalian <handalm@amazon.com>
closes #223 
This change adds a task to publish to a local staging repo under build/ that includes cksums.  It also updates build.sh to use this new task and copy the contents of the staging repo to the output directory.
The maven publish plugin will not include these cksums when publishing to maven local but will when published to a separate folder.
```
./scripts/build.sh -v 1.2.0 -s false
```
```
~/workspace/alerting (maven)$ find ./artifacts/maven/org/opensearch/notification/
./artifacts/maven/org/opensearch/notification/
./artifacts/maven/org/opensearch/notification//maven-metadata.xml.sha256
./artifacts/maven/org/opensearch/notification//maven-metadata.xml …
```
=> Update maven publication to include cksums.

README.md, alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Cherry-picked commits for 1.2 from main
*CheckList:*
=> Release 1.2

.github/workflows/multi-node-test-workflow.yml, DEVELOPER_GUIDE.md, alerting/build.gradle, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/ODFERestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt, build-tools/repositories.gradle, build.gradle
*Issue #, if available:* #147
* Adds backwards compatibility tests for mixed cluster, rolling upgrade and full restart scenarios
* Updates `DEVELOPER_GUIDE` to add instructions for running bwc tests
* Adds bwc tests to the multi-node GitHub Actions tests workflow
A couple improvements that can probably be made in future iterations:
* A hardcoded Monitor in the legacy format (ODFE 1.13.1) is being used for the request on the old version, this is because the `toXContent` method that is being used in the current version of the plugin test is not forwards compatible, so we would need a workaround or some legacy `toXContent` method for `Monitor` if we want to use the `randomMonitor()` helper method for creating the Monitor request
* We can manually update the Monitor …
=> Add backwards compatibility tests

.github/CODEOWNERS
Signed-off-by: CEHENKLE <henkle@amazon.com>
Adding a codeowners file.  Please double check that it's point to the right team in https://github.com/orgs/opensearch-project/teams
*CheckList:*
=> Adding a codeowners file.

README.md
Badge links in README were still pointing to the ODFE Alerting links, updated to point to OpenSearch Alerting.
*CheckList:*
=> Update README badge links to refer to OpenSearch Alerting

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt
*Issue #, if available:* #89
* Fixed the case where if an enabled job is de-scheduled when `SWEEPER_ENABLED` is set to `false`, jobs that were unchanged were not re-scheduled when `SWEEPER_ENABLED` was set to back to `true`
* Added a manual sweep of all shards when `initBackgroundSweep()` is called since the runnable being scheduled in the threadpool is only executed for the first time after the `SWEEPER_PERIOD` (which defaults to 5 minutes) has passed and this could lead to delays in jobs that should run more frequently than that
* Added a test to capture the changes
* Confirmed with an anti-test that the written test failed as expected without the fix
*CheckList:*
[x] Commits are signed per the DCO using …
=> Update sweep logic to re-schedule unchanged jobs when SWEEPER_ENABLED is toggled

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle, build.gradle
Coming from https://github.com/opensearch-project/opensearch-build/issues/1365.
=> Incremented version to 1.2.3.

core/build.gradle
Signed-off-by: Clay Downs <downsrob@amazon.com>
NA
Bumps cron-utils version to 9.1.6 due to CVE.
*CheckList:*
=> Bumps cron-utils version to 9.1.6

.github/workflows/bwc-test-workflow.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml
* Remove `candidate_version` from the reference to OpenSearch docker image since the tags don't include `SNAPSHOT`  for snapshot builds ([reference](https://hub.docker.com/r/opensearchstaging/opensearch/tags))
*CheckList:*
=> Fix running Alerting security tests in GitHub Actions

alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Bug fix for: Admin Users must be able to access all monitors #139
Fix GET /monitor DELETE /monitor when 
`plugins.alerting.filter_by_backend_roles : true`
*CheckList:*
=> Bug fix for: Admin Users must be able to access all monitors #139

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/action/node/ScheduledJobsStatsResponse.kt
The `opendistro` prefixed field response for sweeper/scheduled jobs enabled in the [Alerting Stats API](https://opensearch.org/docs/latest/monitoring-plugins/alerting/api/#monitor-stats) was inadvertently changed to `plugins` during the migration to OpenSearch. This change reintroduces the legacy field back alongside the existing `plugins` one to maintain backwards compatibility and to not break behavior for anyone using the current field.
This PR also updates the existing tests asserting on the response of the stats API to use hardcoded values for the scheduled jobs enabled field instead of referring to the `Setting.key` so it can catch a change like this in the future. We should also …
=> Add back opendistro prefixed sweeper enabled field to alerting stats response

.github/workflows/security-test-workflow.yml
The GitHub Action workflow for running Alerting security tests for `1.1` branch was recently updated to use the non-staging Docker image to pull the OpenSearch image since `1.1.0` was not available in staging. Since `1.1.0` is available in staging now, the workflow is being changed back to be consistent with the other branches.
*CheckList:*
=> Update security test GitHub Action workflow to use Docker staging repo again

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/action/node/ScheduledJobsStatsResponse.kt, core/src/main/kotlin/org/opensearch/alerting/elasticapi/ElasticExtensions.kt
Backport #281 and #283 to `1.x`
*CheckList:*
=> Backport removal of runBlocking and Stats API fix

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/action/node/ScheduledJobsStatsResponse.kt
Backports #283 to `1.0`
*CheckList:*
=> Backport Stats API fix

alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Refactor security integration tests to avoid checking security plugin enabled in every test. 
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
*Issue #, if available:* https://github.com/opensearch-project/alerting/issues/219
*Description of changes:* Refactor security integration tests to avoid checking security plugin enabled in every test. 
*CheckList:*
=> Refactor Security Integration Tests

alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt
*Issue #, if available:* #241
The BWC tests will occasionally fail on the `twoThirdsUpgradedClusterTask`. It seems that there is some race condition that can lead to some test cluster changes to not go through due to the sleep being done in the mixed cluster scenario. For the time being, the sleep will be removed from `MIXED_CLUSTER` scenario as this was shown to remove flakiness.
The sleeps were initially put in to give time for a Monitor execution in between assertions but the current checks in mixed state will suffice. Once we have an easy way to artificially forward Monitor executions (which will likely be after integration with Job Scheduler since the next execution time isn't stored in the Monitor job …
=> Fix flaky BWC test

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
The security tests added as part of #281 were failing but did not get reflected in the recent GitHub Action runs because the workflow was skipping the test since it did not find the security plugin in the `_cat/plugins` response (this still appears as a workflow pass which should also probably be updated). This change is to update the tests so that they work properly. Since the parent change was backported up to `1.1`, the security test fixes will also be backported that far so all test are passing in all relevant branches.
*CheckList:*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Fix security tests with partial permissions

alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/XContentTests.kt
*Issue #, if available:* #126
Update Monitor parse to not use lateinit for name and schedule so it hits the assertion and throws an appropriate IllegalArgumentException when `name` and `schedule` is not present.
*CheckList:*
=> Update Monitor parse to not use lateinit for name and schedule

alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
*Issue #, if available:* #298
Monitor configurations are randomized during the plugin integration tests for the components that aren't being explicitly tested for specific scenarios so the test cases aren't overfit for a single situation. For Bucket-Level Monitors, this could lead to the Actions under a Trigger to sometimes be empty (0 Actions) or contain Actions in such a configuration that it no-ops (i.e. PerExecutionScope with no Alert categories configured). These types of configurations were rare but led to resulting Alerts to either be null (for new Alerts) or not updated (for existing Alerts) in some tests which failed assertions, making these tests flaky. This PR updates those …
=> Fix flaky tests for Bucket-Level Monitor

alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Commented out the flaky tests due to a known issue #300 to unblock build jobs.
```
Tests with failures:
[317](https://github.com/opensearch-project/alerting/runs/5472237725?check_suite_focus=true#step:8:317)
- org.opensearch.alerting.resthandler.SecureMonitorRestApiIT.test query monitors with enable filter by
[318](https://github.com/opensearch-project/alerting/runs/5472237725?check_suite_focus=true#step:8:318)
- org.opensearch.alerting.resthandler.SecureMonitorRestApiIT.test query all alerts in all states with disabled filter by
[319](https://github.com/opensearch-project/alerting/runs/5472237725?check_suite_focus=true#step:8:319)
- org.opensearch.alerting.resthandler.SecureMonitorRestApiIT.test query all alerts in all states with filter by …
```
=> Commented out flaky test in favor of known issue to unblock build

alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Backport #331 to 1.x
*CheckList:*
=> Backport to 1.x : Commented out flaky test in favor of known issue to unblock build (#331)

alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Backport https://github.com/opensearch-project/alerting/pull/331 to 1.3
*CheckList:*
=> Backport to 1.3 : Commented out flaky test in favor of known issue to unblock build

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/SupportedClusterMetricsSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/SupportedClusterMetricsSettingsExtensions.kt, alerting/src/main/resources/org/opensearch/alerting/settings/supported_json_payloads.json, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/SupportedClusterMetricsSettingsExtensionsTests.kt, core/build.gradle, core/src/main/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInput.kt, core/src/test/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInputTests.kt
* Implemented support for LocalUriInput monitors.
* Refactored feature naming convention from LocalUriInput to ClusterMetricsInput. Added Cluster Metrics as a new monitor type to align with frontend experience.
* Fixed ktlint errors.
* Implemented randomClusterMetricsMonitor test helper, and refactored tests accordingly.
* Renamed some assets to align with the new name for this feature.
* Refactored cluster metrics feature to remove support for Cat repositories API.
* Refactored supported JSON payload to return …
=> Implemented support for ClusterMetrics monitors (#221)

.github/workflows/backport.yml, .github/workflows/delete_backport_branch.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml, DEVELOPER_GUIDE.md, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/SupportedClusterMetricsSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/SupportedClusterMetricsSettingsExtensions.kt, alerting/src/main/resources/org/opensearch/alerting/settings/supported_json_payloads.json, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/SupportedClusterMetricsSettingsExtensionsTests.kt, core/build.gradle, core/src/main/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInput.kt, core/src/test/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInputTests.kt, release-notes/opensearch-alerting.release-notes-1.3.0.0.md
https://github.com/opensearch-project/alerting/issues/314
Cherry-picking commits [df65ffc](https://github.com/opensearch-project/alerting/commit/df65ffcc87a0c9c9adb87ddf9cedc1d5544e64dc) through [9487c00](https://github.com/opensearch-project/alerting/commit/9487c00a388dbc3d9a5bce602a2b70b0ec20f90f) from `opensearch-project/alerting/main` to `opensearch-project/alerting/1.x`.
*CheckList:*
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#de …
=> Cherry-picking commits for 1.3 release from main to 1.x

.github/ISSUE_TEMPLATE/bug_report.md
Removed the `Beta` label from the bug report template.
*CheckList:*
=> Removed the Beta label from the bug report template.

alerting/src/main/kotlin/org/opensearch/alerting/action/AcknowledgeAlertAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/DeleteDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/DeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/ExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/IndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/IndexEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/IndexEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/IndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/SearchEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/SearchEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/SearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/SupportedClusterMetricsSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/SupportedClusterMetricsSettingsExtensionsTests.kt, build-tools/merged-coverage.gradle, build.gradle, core/src/main/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInput.kt, core/src/test/kotlin/org/opensearch/alerting/core/model/ClusterMetricsInputTests.kt
N/A
- Upgrade kotlin to 1.6.10
*CheckList:*
[C] Commits are signed per the DCO using --signoff
=> Upgrade kotlin to 1.16.10

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTrigger.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTriggerRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Trigger.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/TriggerScript.kt, alerting/src/main/resources/org/opensearch/alerting/org.opensearch.alerting.txt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/WriteableTests.kt
Add connection to triggers for doc level alerting
*CheckList:*
=> Add connection to triggers for doc level alerting

alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Signed-off-by: jiahe zhang <zhanncha@amazon.com>
https://github.com/opensearch-project/alerting/pull/349
https://github.com/opensearch-project/alerting/pull/324
For the Create/Update APIs, ensure there is validation to ensure the monitor is defined correctly. Also in general for the APIs, ensure there no issues when executing the CRUD APIs on doc level monitor and the other monitor types based on the changes
*CheckList:* …
=> CRUD APIs integration Tests and validation"conflict resolved"

.github/workflows/bwc-test-workflow.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/test/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregatorTests.kt, build.gradle, core/src/main/kotlin/org/opensearch/alerting/core/ScheduledJobIndices.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/ScheduledJob.kt
* Bumps OpenSearch version being used from `2.0.0` to `2.0.0-alpha1`
* Removes mapping type usage
* Adds `-Dbuild.qualifier=alpha1` to the GitHub Actions to ensure we're using `alpha` for dependencies as well (i.e. `common-utils`)
The security workflow is still expected to fail for now since the Docker image with security plugin 2.0 is not available yet.
*CheckList:*
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of …
=> Use OpenSearch 2.0.0-alpha1

scripts/build.sh
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
#348
Make sure alerting is using the build script in its own repo
We have 2 Alerting build script, one in build repo one in Alerting repo.
Our code base define that build repo script take priority over the Alerting repo script.
It would be better for Alerting to host their own build script in Alerting repo.
This is a pre-requisite to keep both script consistent before we remove the build script from build repo.
Example existing calls:
```
2022-03-29 18:42:25 INFO     Executing "bash /var/jenkins/workspace/distribution-build-opensearch/scripts/components/alerting/build.sh -v 1.3.1 -p linux -a arm64 -s false -o builds" in /tmp/tmpz94r2nd7/alerting
```
*CheckList:*
[x] Commits are signed per the …
=> Make sure alerting is using the build script in its own repo

.github/workflows/bwc-test-workflow.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/model/BucketLevelTriggerRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetDestinationsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexDestinationAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexEmailAccountAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexEmailGroupAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerIT.kt, build.gradle
* #327 Add JDK 17 support
* #374 Remove JDK 14 support
*CheckList:*
=> Remove JDK 14 and Add JDK 17

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentReturningMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Alert.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Finding.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json, alerting/src/main/resources/org/opensearch/alerting/findings/finding_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/AcknowledgeAlertResponseTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetAlertsResponseTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/DocLevelMonitorInputTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/FindingTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/DocLevelMonitorInput.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/DocLevelQuery.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/Input.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/SearchInput.kt
N/A
- Add action and alert flow
- Add finding schema
- Add integ tests
- Add fixes
*CheckList:*
=> Add action and alert flow and findings schema and additional fixes

alerting/src/main/kotlin/org/opensearch/alerting/DocumentReturningMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/parsers/ExpressionParser.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/parsers/TriggerExpressionParser.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/parsers/TriggerExpressionRPNBaseParser.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/resolvers/TriggerExpression.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/resolvers/TriggerExpressionRPNResolver.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/resolvers/TriggerExpressionResolver.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/tokens/ExpressionToken.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/tokens/TriggerExpressionConstant.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/tokens/TriggerExpressionOperator.kt, alerting/src/main/kotlin/org/opensearch/alerting/triggercondition/tokens/TriggerExpressionToken.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionParserTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
Add Trigger condition parser which parses the provided trigger condition expression in the Reverse Polish Notation and then 
resolves the final set of Document Ids which matches the given expression for Document Level Alerts.
Users can configure the Trigger condition using the expression strings as below:
**Always True**
``
return true
``
**Always False**
``
return false
``
**Query Expressions**
```
* (query[name=sigma-123] && query[name=sigma-456]) || (!query[id=aert34df] && query[tag=sev2])
* query[tag=sev1]
* (query[name=sigma-123] && query[tag=sev2]) || (!query[tag=sev3] && query[id=dfd457iy] && query[tag=“sev1"])
```
Operartors supported are:
```
* (
* )
* &&
* ||
* !
```
Query Identifiers supported are:
```
* name ---> query[name=sigma-123]
* tag ---> query[tag=sev2]
* id ---> …
```
=> Add Trigger condition parser and resolver for Doc Level Alerts

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Chime.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Destination.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Slack.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/DestinationSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationConversionUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationUtilService.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt, notification/src/main/java/org/opensearch/alerting/destination/client/DestinationEmailClient.java
*Issue #, if available:* #105
This PR depends on https://github.com/opensearch-project/common-utils/pull/158 and https://github.com/opensearch-project/notifications/pull/406 so the GitHub Actions are expected to fail without at least `common-utils` being merged in
The main changes in this PR are:
* Integrating with the Notifications plugin, supporting execution of the notification actions before/after migration of the Destination configs to Notifications
* In the case of the Destination failing migration, it will be sent through the passthrough API (this avoids hard failures on a write block but still requires the Notification plugin to be installed since the passthrough API does not work without it)
* Fixes some bugs
* For the Destination migration, …
=> Integrate with Notifications plugin for Alerting backend

alerting/build.gradle, alerting/src/main/java/org/opensearch/percolator/PercolateQueryBuilderExt.java, alerting/src/main/java/org/opensearch/percolator/PercolatorFieldMapperExt.java, alerting/src/main/java/org/opensearch/percolator/PercolatorPluginExt.java, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentReturningMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/FindingDocument.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/FindingWithDocs.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/settings/AlertingSettingsTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/settings/DestinationSettingsTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionParserTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/ScheduledJob.kt, core/src/main/resources/mappings/doc-level-queries.json
percolate query implementation in doc-level alerting
[Percolate Query implementation in Document Level Alerting](https://github.com/opensearch-project/alerting/issues/387)
This PR provides Percolate Query based implementation in Document Level Alerting. It implements the following design with its limitations.
*CheckList:*
[X] Integration tests work for doc-level alerting
[ ] Performance test results - pending
[ ] Additional tests …
=> Percolate Query implementation in doc-level alerting

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt
[Deprecate the "Master" nomenclature](https://github.com/opensearch-project/alerting/issues/320)
Replace the terminology "master" with "cluster manager".
*CheckList:*
=> Deprecate the Master nomenclature in 2.0

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt
Signed-off-by: Ravi Thaluru <thalurur@users.noreply.github.com>
N/A
Keep seeing following errors on cluster - skipping Destination migration if alert index is not initialized
```
[2022-04-20T20:04:42,752][ERROR][o.o.a.u.d.DestinationMigrationCoordinator] [dev-dsk-rthaluru-2b-5db44ff7.us-west-2.amazon.com] Failed to migrate destination data
org.opensearch.index.IndexNotFoundException: no such index [.opendistro-alerting-config]
at org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:1055) ~[opensearch-2.0.0-rc1.jar:2.0.0-rc1]
at org.opensearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolv …
```
=> Skipping destination migration if alerting index is not initialized

alerting/build.gradle, build.gradle
#438
- Remove rc1 qualifier from plugin version
*CheckList:*
=> Remove rc1 qualifier from plugin version

alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Alert.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTrigger.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt, alerting/src/main/resources/org/opensearch/alerting/org.opensearch.alerting.txt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/DocLevelQuery.kt
N/A
- Fix Minor bugs
- Pass in user context when retrieving user's notification channels
- Fix action execution for DocLevel monitors where actions are to run per trigger execution
- Fix bug that did not generate all the alerts for monitors with multiple indices in Document Level Monitors
- Add Findings ID and document ID to action template
*CheckList:*
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CO …
=> Fix minor bugs and pass in user context when retrieving user's notification channels

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Alert.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/AlertingConfigAccessor.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTriggerRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/MonitorMetadata.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/action/ActionExecutionPolicy.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/ADTestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorResponseTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/IndexMonitorResponseTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/DocLevelMonitorInputTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/WriteableTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/XContentTests.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/DocLevelQuery.kt, core/src/main/resources/mappings/scheduled-jobs.json
Fix minor bugs and support per alert action execution for Document Level Monitors (#441)
* Fix minor bugs as well as support per alert action execution for DocLevelMonitors
N/A
- backport #441
- 
*CheckList:*
=> Fix minor bugs and support per alert action execution for Document Level Monitors

alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/Alert.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTrigger.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt, alerting/src/main/resources/org/opensearch/alerting/org.opensearch.alerting.txt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/model/DocLevelQuery.kt
- Fix minor bugs and pass in user context when retrieving user's notification channels
- Backport #447 
*CheckList:*
=> [Backport 2.0] Fix minor bugs and pass in user context when retrieving user's notification channels

alerting/build.gradle, scripts/build.sh, settings.gradle
#435
Uses custom plugin to publish zips to maven
*CheckList:*
=> Uses custom plugin to publish zips to maven

alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt
fixes #311 
Add support for int datatype as bucket keyField
*CheckList:*
=> add support for int key in bucket level trigger aggregations

build.gradle
*Add support for reproducible builds*
As per gradle [docs] add support to remove timestamps and package with same order which is required from
[reproducible] builds
[docs]: https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
[reproducible]: https://reproducible-builds.org/
*CheckList:*
=> Add support for reproducible builds

README.md
Signed-off-by: cwillum <cwmmoore@amazon.com>
*Description of changes*
Replace the link to Forum discussion in the README.md file so that it points to the OpenSearch forum rather than the defunct Open Distro forum.
*CheckList:*
This fixes the issue for the Alerting plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).
=> Replace Forum link in Alerting plugin README.md

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt
[Deprecate the "Master" nomenclature](https://github.com/opensearch-project/alerting/issues/320)
this replaces the deprecated api `localNodeMaster` to `localNodeClusterManager`.
*CheckList:*
=> Deprecate the Master nomenclature in 2.3

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt, core/src/main/resources/mappings/scheduled-jobs.json
Backport monitor datasources to 2.x
=> backport monitor datasources to 2.x

alerting/src/main/kotlin/org/opensearch/alerting/action/GetAlertsRequest.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetAlertsRequestTests.kt
Adds support for fetching alerts from custom alert index in Get Alerts transport layer
Related Issues:
#562 #522
=> Adds support for fetching alerts from custom alert index in Get Alerts transport layer

alerting/src/main/kotlin/org/opensearch/alerting/action/GetFindingsRequest.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetFindingsRequestTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Signed-off-by: Petar Dzepina <petar.dzepina@vroom.com>
Added **_monitorId_** and **_findingsIndexName_** optinal params to GetFindings Action. These will be used to reference finding index, instead of default hardcoded one. **_findingsIndexName_** has higher priority over _**monitorId**_
*CheckList:*
=> GetFindingsAction new optional parameters

scripts/build.sh
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
https://github.com/opensearch-project/alerting/issues/557
Disable ktlint for alerting as it has errors on Windows
*CheckList:*
=> Disable ktlint for alerting as it has errors on Windows

alerting/src/main/kotlin/org/opensearch/alerting/model/Monitor.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, core/src/main/resources/mappings/scheduled-jobs.json
[[FEATURE] Support Data Segregation for Monitors created from other client plugins](#576)
=> Adds owner field in monitor model

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
When updating a monitor with new custom query index (possibly) we need to delete queries from the monitor's current query index
=> Use custom query index in update monitor flow

alerting/build.gradle, build.gradle
Bumps alerting to 2.4
This PR also bumps org.mockito:mockito-core dependency  to 4.7.0
=> Bumps alerting to 2.4

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
fix bug in `doc-level alerting` logic that `tags are not passed to trigger conditions parser`
*CheckList:*
=> add tags to trigger condition of doc-level monitor

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt
Change transport ack alerts action to accept Action Request and recreate as AckAlertRequest to fix Acknowledge Alert Request class loader issue
Solving the same issue we faced earlier with notifications for ack alerts flow : https://github.com/opensearch-project/common-utils/issues/37
=> Fix Acknowledge Alert Request class loader issue

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
=> fix alias exists check in findings index creation

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Ack alerts - allow moving alerts to history index with custom datasources
*CheckList:*
=> Ack alerts - allow moving alerts to history index with custom datasources

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt
Backports https://github.com/opensearch-project/alerting/pull/628
=> [Backport] Refactored DeleteMonitor Action to be synchronous

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, core/src/main/resources/mappings/scheduled-jobs.json
=> adds filtering on owner field in search monitor action

.github/workflows/security-test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
#138 
Support specify backend roles for monitors
New Scenarios:
- Create monitor scenario:
- User specified backend roles
- Admin user: use all the specified backend roles to associate to the monitor
- Normal user: use all the specified backend roles (that the user already has in their list of backend roles) to associate to the monitor
- User did not specify backend roles:
- Copy user’s backend roles and associate them to the monitor
- Update monitor scenario:
- User specified backend roles
- Admin user: Remove all the backend roles associate to the monitor and then use all the specified backend roles to associate to the monitor
- Normal user: Remove backend roles associated to the …
=> Support to specify backend roles for monitors

release-notes/opensearch-alerting.release-notes-2.4.0.0.md
N/A
Add 2.4 release notes
*CheckList:*
=> Add 2.4 release notes

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertServiceTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
This change surfaces out the list of documents that become a part of bucket level monitor aggregation buckets as findings for the monitor.
*CheckList:*
=> Adds findings in bucket level monitor 

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Fixed bug where findingIndex would be recreated in some situations because of faulty "exists" check
*CheckList:*
=> create findingIndex bugfix

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Fixed bug where PUT _mapping against query index would fail in case of "nested" properties in index mappings
*CheckList:*
=> Added support for "nested" mappings

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Fixed few bugs with index mappings traversal which resulted in monitors not working.
*CheckList:*
=> mappings traversal bug fix

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
=> mappings traversal bug fix (#669) backport to 2.4

.github/workflows/test-workflow.yml, scripts/build.sh
[#684](https://github.com/opensearch-project/alerting/issues/684)
*CheckList:*
=> fix for windows ktlint issue

alerting/src/main/kotlin/org/opensearch/alerting/model/destination/Destination.kt
Signed-off-by: Petar Partlov <partlov@gmail.com>
While testing legacy destinations for custom webhooks I discovered issue which is 100% reproducible. Scope should not be huge as this can influence only users with some issue during migration of old legacy notification system to new which uses notification plugin.
Issue is that one of required field (message) was not set during building instance of LegacyCustomWebhookMessage object.
*CheckList:* …
=> Set message when building LegacyCustomWebhookMessage

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
#703 
Seperate variables for alert and finding scheduled rollovers to prevent both tasks to get cancelled
*CheckList:*
=> Seperate variables for alert and finding scheduled rollovers

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt
N/A
When the destination or notification channel cannot be found, the error message shows the action Id instead of the destination/notification id.
*CheckList:*
=> Fix error message bug to show the correct destination ID thats missing

alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt
*Issue #, if available:* [578](https://github.com/opensearch-project/notifications/issues/578)
Using subject instead of defaultTitle if possible
*CheckList:*
=> Overriding defaultTitle with subject for SNS notifications

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/AlertingConfigAccessor.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/MonitorMetadata.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/XContentTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt, core/src/main/resources/mappings/scheduled-jobs.json
=> [Backport 2.x] QueryIndex rollover when field mapping limit is reached.

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
Added unwrapping exceptions from core. Also added more debug logs
*CheckList:*
=> Added unwrapping exceptions from core

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Signed-off-by: Raj Chakravarthi <raj@icedome.ca>
https://github.com/opensearch-project/security-analytics/issues/172
if mapping had a field named "type" the recursive mapping traversal ignored peer nodes
*CheckList:*
=> fix  percolator mapping error when having field name 'type'

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
fix for ERROR alert state generation in doc-level monitors
*CheckList:*
=> fix for ERROR alert state generation in doc-level monitors

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Fixed ExecuteMonitor Action inserting metadata doc during dryrun
*CheckList:*
=> [BUG] ExecuteMonitor inserting metadata doc during dry run

alerting/build.gradle, alerting/src/main/java/org/opensearch/percolator/PercolateQueryBuilderExt.java, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/plugin-metadata/plugin-security.policy, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, core/src/main/resources/settings/doc-level-queries.json
#775
Added adjusting max field index setting dynamically for query index
*CheckList:*
=> Adjusting max field index setting dynamically for query index

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt
#529, #731
Set default title only when there is no subject passed.
action message configuration example:
Current message look in chime:
Before Notification plugin introduction in chime:
With the fix look in chime:
With the fix for SNS:
*CheckList:*
=> Fix setting default title only when no subject has been set

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt
N/A
Backport https://github.com/opensearch-project/alerting/commit/830dff1d17c9a002efe417b55b84219b14c0c2fe from https://github.com/opensearch-project/alerting/pull/750
*CheckList:*
=> [Backport 2.5] Fix setting default title only when no subject has been set

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
* fixed security tests
Signed-off-by: Raj Chakravarthi <raj@icedome.ca>
(cherry picked from commit c51940f5e2d14a00262f7f4675bbba2d930d2ede)
*CheckList:*
=> fixed security tests (#484)

alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
Fixed cluster metrics monitor tests following common-utils bug fix in PR https://github.com/opensearch-project/common-utils/pull/359.
For context, the bug was only present on the common-utils 3.0 branch, so this PR **does not need to be backported**.
*CheckList:*
=> Fixed cluster metrics monitor tests following common-utils bug fix.

core/src/main/resources/mappings/scheduled-jobs.json
minor fix to prevent flaky tests in downstream plugins
sample flaky run: https://github.com/phaseshiftg/security-analytics/actions/runs/4228665096/jobs/7344314835
https://stackoverflow.com/questions/58644738/update-a-field-from-a-elasticsearch-document
https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html
*CheckList:*
=> minor fix to prevent flaky tests in downstream plugins

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
#783 
Added support for multiple indices support in DocLevelMonitorInput
*CheckList:*
=> Multiple indices support in DocLevelMonitorInput

release-notes/opensearch-alerting.release-notes-2.6.0.0.md
N/A
Added 2.6 release notes.
*CheckList:*
=> Added 2.6 release notes.

alerting/build.gradle
N/A
* Use notification snapshot for integ test
* This improves stability for the tests when ci builds are not done.
*CheckList:*
=> Use notification snapshot for integ test

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/WorkflowSingleNodeTestCase.kt, core/build.gradle, core/src/main/resources/mappings/scheduled-jobs.json
#834 
Added transport layer for creating/updating of the workflows and appropriate integration tests
*CheckList:*
=> Added layer for creating and updating the workflow

alerting/build.gradle
Adjusted mockito dependency to retrieve the version from [OpenSearch core](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L52).
*CheckList:*
=> Adjusted mockito dependency to retrieve the version from OpenSearch core.

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/WorkflowSingleNodeTestCase.kt
=> Dependency fix

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
*Issue #, if available:* #844
Fixed transformation of document field names before running percolator search.
Documents which are ingested with "nested fields" weren't handled properly. Example:
```
"field1": {
"field2": 12345
}
```
*CheckList:*
=> Fixed transformation of document field names before running percolator search

core/build.gradle
N/A
Use latest common-utils snapshot. This allows alerting ci builds to pick up the latest changes from common-utils instead of waiting for successful build distribution from infrastructure. 
*CheckList:*
=> Use latest common-utils snapshot

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
fixed mappings parsing when field name named "properties" exists in mappings
*CheckList:*
=> Mappings parsing fix

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
#841 
Update config index schema if needed at the start of each monitor execution. This fixes issues when upgrading the cluster where the index mapping changed and the user has not indexed or updated a new monitor yet.
*CheckList:*
=> Update config index schema if needed at the start of each monitor execution

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
#842
Fix getAlerts API for standard Alerting monitors since it was defaulting to searching the alerts index instead of `ALL_ALERT_INDEX_PATTERN`
*CheckList:*
=> Fix getAlerts API for standard Alerting monitors

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
#842
Backport #870
*CheckList:*
=> [Backport 2.7] Fix getAlerts API for standard Alerting monitors (#870)

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
#842
Backport #870
*CheckList:*
=> [Backport 2.x] Fix getAlerts API for standard Alerting monitors (#870)

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
integrate security-analytics & alerting for correlation engine
*CheckList:*
=> integrate security-analytics & alerting for correlation engine

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
DocLevel Monitors generate findings when there's no triggers defined
*CheckList:*
=> DocLevel Monitor - generate findings when 0 triggers

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
1. Fixed a bug that prevented alerts from being generated for doc level monitors that use wildcard characters in index names.
2. Fixed integration tests that examine this use case.
*CheckList:*
=> Fixed a bug that prevented alerts from being generated for doc level monitors that use wildcard characters in index names.

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
#817
Specific "Error Alert" is created for a monitor, when error happens during monitor run. State of alert is ERROR and subsequent errors would upsert this "Error Alert". If error message is different then previous one, errorMessage field would be overwritten and previous error would be added to errorHistory rolling array(10 elements).
*CheckList:*
=> DocLevelMonitor Error Alert - rework

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
*Issue #, if available:* #892
*CheckList:*
=> Backport 892 to 2.x

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
Specific "Error Alert" is created for a monitor, when error happens during monitor run. State of alert is ERROR and subsequent errors would upsert this "Error Alert". If error message is different then previous one, errorMessage field would be overwritten and previous error would be added to errorHistory rolling array(10 elements). ---------
(cherry picked from commit 461e95f38bd55268e3ac17026e283ac9f18d911b)
*CheckList:*
For more information on following Developer Certificate of Origin and signing off your commits, …
=> DocLevelMonitor Error Alert - rework (#892)

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
In Monitor creation flow adds logic to log correct error message and clean up monitor when there is failure in indexing doc level queries or in monitor metadata creation.
Secure test run
```
alerting git:(secure-test) ✗ ./gradlew :alerting:integTest -xktlint -Dtest.debug=1  -Dcluster.debug=1 -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=docker-cluster -Dsecurity=true -Dhttps=true -Duser=admin -Dpassword=admin --stacktrace --tests "org.opensearch.alerting.resthandler.SecureMonitorRestApiIT.test create monitor failure clean up with a user without delete monitor access"
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 7.4.2
OS Info               : Mac OS X 13.3 (x86_64)
JDK Version           : 17 …
```
=> log error messages and clean up monitor when indexing doc level queries or metadata creation fails

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
#897
In Monitor creation flow adds logic to log correct error message and clean up monitor when there is failure in indexing doc level queries or in monitor metadata creation.
*CheckList:*
=> Backports #900 clean up monitor when indexing doc level queries or metadata creation fails 

alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/WorkflowRunnerIT.kt
=> Updated alert mapping to consider wotkflow_execution_id

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
…r search (#845)
* Fixed transformation of document field names before running percolator search
(cherry picked from commit 702da92495481bebfc18dbee2de9544a4245759a)
#844
*CheckList:*
=> doc transform 2.5 backport

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt
Metadata is required for correct query index clean up during monitor deletion. Reverted to deleting monitor metadata after deleting doc level queries to fix regression.
=> revert to deleting monitor metadata after deleting doc level queries to fix delete monitor regression.

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
Manual backport of changes in PR #845.
*CheckList:*
=> [Backport 2.3] Fixed transformation of document field names before running percolator search

.github/PULL_REQUEST_TEMPLATE.md, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
This change is to accommodate security plugin change https://github.com/opensearch-project/security/pull/2784
*CheckList:*
=> Use strong password in security test

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/opensearchapi/OpenSearchExtensions.kt
This PR manually backports PRs #728, #729, #784, #861, and #900.
For context, the following PRs were identified as needing backport to the 2.5 branch. Some of them were able to be backported automatically; the backport PR is listed next to those PRs for reference. Some of the changes were already present in the 2.5 branch.
1. https://github.com/opensearch-project/alerting/pull/728
2. https://github.com/opensearch-project/alerting/pull/729
3. https://github.com/opensearch-project/alerting/pull/750 -> https://github.com/opensearch-project/alerting/pull/786
4. https://github.com/opensearch-project/alerting/pull/758 -> https://github.com/opensearch-project/alerting/pull/778
5. https://github.com/opensearch-project/alerting/pull/768 -> …
=> [Backport 2.5] Manual backports of several PRs

.github/PULL_REQUEST_TEMPLATE.md, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Backport https://github.com/opensearch-project/alerting/pull/933
*CheckList:*
=> Use strong password in security test (#933)

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexWorkflowAction.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Added rest layer for the workflow. Added secure tests and rest tests.
Feature branch PR merged: **[Added rest layer for the workflow. Added secure tests]( #886)**
*CheckList:*
=> Added rest layer for the workflow.

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexWorkflowAction.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Backport #963 
* Added rest layer for the workflow. Added secure tests (#886)
* Added rest layer for the workflow. Added secure tests
* add execution_id field in alert mapping
=> Added rest layer for workflows (Backport #963)

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json
fix alert constructor with noop trigger to use execution id and workflow id, syncing with common utils changes
=> fix alert constructor with noop trigger to use execution id and workflow id

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
1. Fixed a bug in the search monitor API when which prevent alert counts from being returned.
2. Implemented integ test for frontend use case.
*CheckList:*
=> Fixed search monitor API to return alert counts.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Manual backport of PR https://github.com/opensearch-project/alerting/pull/978
*CheckList:*
=> [Backport 2.x] Fixed search monitor API to return alert counts.

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
#955 
Fix getAlerts RBAC problem, when the monitor ID was specified. This was due to calling another transport call when the context was stashed making the plugin believe security was not enabled.
*CheckList:*
=> Fix getAlerts RBAC problem

alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
*Issue #, if available: #798
*CheckList:*
=> [BucketLevelMonitor] Multi-term agg support

alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/SupportedClusterMetricsSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesHelpers.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsHelpers.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/SupportedClusterMetricsSettingsExtensions.kt, alerting/src/main/resources/org/opensearch/alerting/settings/supported_json_payloads.json, alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesWrappersIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsWrappersIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/SupportedClusterMetricsSettingsExtensionsTests.kt
https://github.com/opensearch-project/alerting/issues/611
Implemented support for configuring a cluster metrics monitor to call cat/indices, and cat/shards.
Documentation issue https://github.com/opensearch-project/documentation-website/issues/4437
*CheckList:*
=> Implemented support for configuring a cluster metrics monitor to call cat/indices, and cat/shards.

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertMover.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Added workflowIds field in Get Alerts rest API 
This allows users to fetch chained alerts when listing workflows and monitor in the dashboard
=> Add workflowIds field in getAlerts API

alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
fix password argument in SecureRestClientBuilder constructor for SecureWorkflowRestApiIT
=> fix password argument in SecureRestClientBuilder constructor for SecureWorkflowRestApiIT

alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/SupportedClusterMetricsSettingsExtensions.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesWrappersIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsWrappersIT.kt
N/A
Update actionGet to SuspendUntil for ClusterMetrics API calls
*CheckList:*
=> Update actionGet to SuspendUntil for ClusterMetrics

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetWorkflowAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Get chained alert API will support filtering based on an alertId. The motivation is to fetch associated alerts with support for pagination. The size and sort params would apply to fetch associated alerts in this api when alert id is mentioned
=> add alertId parameter in get chained alert API and paginate associated alerts if alertId param is mentioned

core/build.gradle
=> Remove googlejavaformat to address guava CVE-2023-2976

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/ChainedAlertTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Backports https://github.com/opensearch-project/alerting/pull/1079 as main branch is unstable pending on fixes from Opensearch core's breaking change refactor on dependencies.
=> Backports #1079 (Chained Alert Behaviour Changes )

core/build.gradle
Exclude <v32 version of google guava in google java format and add google guava 32.0.1 to resolve CVE CVE-2023-2976
=> upgrade google guava 32.0.1 to resolve CVE CVE-2023-2976

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/build.gradle
N/A
Update the BWC version to fix the BWC tests as `mixedClusterTask` and `rollingUpgradeClusterTask` needs the previous major version to be the latest (eg. Needs to be 2.10 vs 2.6)
*CheckList:*
=> Update BWC version to fix BWC tests

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/ChainedAlertTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Context:
---
Workflow/Composite monitor supports triggers whose conditions are configured as Boolean conditions with AND, OR, NOT
Operators and monitors as variables. For ex. Trigger condition M1 && M2 means trigger condition is matched if both monitors M1 and M2 create alerts (in AUDIT state) in the current execution. If workflow trigger condition is matched we create Chained Alert.
Current behavior
---
Alerts are created in ACTIVE state. 
When alert are acknowledged they move to ACKNOWLEDGED state.
New behavior introduced with this PR
===
**- If no ACTIVE/ACKNOWLEDGEDstate alert already exists for composite monitor trigger, we create a new ACTIVE state alert.**
**- If ACTIVE/ACKNOWLEDGED state alert already exists, we update that alert’s lastNotificationTime itself. But we do NOT create …
=> Chained Alert Behaviour Changes

alerting/src/main/kotlin/org/opensearch/alerting/WorkflowService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Adds support for using a list monitor ids in chained monitor findings. This helps use input data for a monitor in workflow based on doc ids from findings of multiple monitors instead of a single monitor.
If workflow sequence looks like:
[m1] -> [m2] -> [m3 (chained findings of m1, m2)]
this means m3's data input would be the related doc ids from findings of m1 and m2.
In a given workflow execution the following scenarios may occur:
Scenario 1:
if m1 has findings related to docs 1,2,3 of "index1"
if m2 has findings related to docs 3,4,5 of "index1"
m3's source data would be docs 1,2,3,4,5 of index 1
Scenario 2:
if m1 has findings related to docs 1,2,3 of "index1"
if m2 has findings related to docs 3,4,5 of "index2"
m3's source data would be docs 1,2,3 of "index1" and "index2"
Scenario 3: …
=> Adds support for using findings from list of monitors as input data for a monitor in workflow

alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
In workflows, we save audit state alerts from delegate monitors.
Within the same workflow execution we execute a search request to fetch the persisted audit alerts from alerts system index.
Since RAW guarantees have changed with seg rep, we would need to search on primaries to ensure we have the latest information.
Relates to [Compatibility with segment replication #974
](https://github.com/opensearch-project/alerting/issues/974)
=> Changes in workflows for seg rep compatibility

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
This pr addresses following performance problems in `doc-level monitor execution workflow`.
- In the current workflow, if the `doc-level monitor` is monitoring an `index pattern` & a new index is introduced which matches the pattern, the `doc-level monitor` duplicates all the field mappings & queries for that index. This is reproducible using integ test https://github.com/opensearch-project/alerting/pull/1097/files#diff-9b08d53e8cff3d739beb6ba304e4eaf466f08412762c3cd55886a52b722a77f1R503
Now, say, we have `1000` queries & each concrete index behind the index-pattern has 1000 field mappings. Also, lets assume `1 concrete index` is generated everyday. We also know the `default number of field mappings` an index can have is `1000` & today if the no. of field …
=> optimize doc-level monitor workflow for index patterns

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
add workflow null or empty check only when empty workflow id passed in transport get alerts request.
In Rest get alert action,  add empty string singleton list for workflow ids when none is passed. This is to support returning non-Audit alerts on Alert Dashboard.
=> add workflow null or empty check only when empty workflow id passed.

alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
Ignoring secure workflow tests as they are flaky in jenkins CI
investigate flaky nature of tests. not reproducible in local but fails in jenkins CI
=> ignore flaky security tests

alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
N/A
Ignore flaky security tests for 2.10
*CheckList:*
=> Ignore flaky security test suites

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
#974
Add primary first calls for different monitor types in Alerting to handle segment replication.
*CheckList:*
=> Add primary first calls for different monitor types

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
https://github.com/opensearch-project/security-analytics/issues/606
*CheckList:*
=> fix workflow execution for first run

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
#41
Add logging around monitor and workflow executions, creations, and updates.
*CheckList:*
=> Add logging for execution and indexes of monitors and workflows

alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
In org.opensearch.alerting.alerts/AlertIndices there is a log message "info deleteOldIndices" which is more of a trace but it is logged with level error.
In my logs see the following entries (repeated every 12 hours):
```
Oct  2 07:47:08 hostname opensearch[414]: [2023-10-02T07:47:08,760][ERROR][o.o.a.a.AlertIndices     ] [n1-name] info deleteOldIndices
Oct  2 07:47:08 hostname opensearch[414]: [2023-10-02T07:47:08,823][ERROR][o.o.a.a.AlertIndices     ] [n1-name] info deleteOldIndices
Oct  2 19:47:08 hostname opensearch[414]: [2023-10-02T19:47:08,761][ERROR][o.o.a.a.AlertIndices     ] [n1-name] info deleteOldIndices
Oct  2 19:47:08 hostname opensearch[414]: [2023-10-02T19:47:08,825][ERROR][o.o.a.a.AlertIndices     ] [n1-name] info deleteOldIndices
```
This is …
=> Reduce log level for informative message

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
=> Handle Doc level query 'fields' param for query string query 

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Backports 2.x commits:
[Backport 2.x] Add logging for execution and indexes of monitors and workflows #1224
optimize doc-level monitor workflow for index patterns #1122
[Backport 2.x] fix for concurrentmodificationexception with linkedhashmap #1259
=> Backport bug fixes to 2.9

alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
Closes #1244 
Changed @Ignore to @AwaitsFix in SecureWorkflowRestApiIT
*CheckList:*
=> Changed @Ignore to @AwaitsFix

alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/6514/pipeline/118/
fix workflow security tests in alerting
*CheckList:*
=> fix workflow security tests in alerting

release-notes/opensearch-alerting.release-notes-2.11.1.0.md
Commits reverted:  c00c86d360b80b8e3b91795b799e2f5b7f590a3b. 
*CheckList:*
=> remove PRs reverted commit from release notes

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
#1290 
This pr optimizes the doc-level monitor execution workflow for data streams.
The optimization proposed only considers the `current write index, any new read-only indices created after last monitor execution run & the last write index of last monitor execution run` for current monitor execution run.
It ignores `read-only indices` that may have been created prior to the last monitor execution run.
The below diagram shows the difference.
**Earlier**
**Now**
*CheckList:* …
=> optimize doc-level monitor execution workflow for datastreams

alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
=> fix code conflicts

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt
*Issue #, if available:* https://github.com/opensearch-project/security-analytics/issues/718
* Add additional check for docData being null in Findings. If so, set to empty string
*CheckList:*
=> Set docData to empty string if actual is null

alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
Notifications added validation to the Chime webhook URL a few weeks ago. This PR updates the webhook URL used in tests to adhere to the validation requirements to fix a broken test.
Notification validation was added as part of this commit: https://github.com/opensearch-project/notifications/commit/1163d542a6028faeb7941349ea9232f1c490a45d
*CheckList:*
=> Add token to chime URL used in tests to adhere to new Notifications validation

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
Partially https://github.com/opensearch-project/security-analytics/issues/618
The DeleteWorkflow action attempts to parse the Workflow object when reading it before delete, even if the Workflow was not found. This leads to an NPE:
```
[2023-12-21T11:55:00,674][ERROR][o.o.a.t.TransportDeleteWorkflowAction] [integTest-0] Failed to delete workflow WWvxjYwBC1VdWUdNmDay
java.lang.NullPointerException: Cannot invoke "org.opensearch.core.common.bytes.BytesReference.length()" because "bytes" is null
at org.opensearch.compress.ZstdCompressor.isCompressed(ZstdCompressor.java:66) ~[opensearch-compress-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
at org.opensearch.core.compress.CompressorRegistry.compressor(CompressorRegistry.java:65) …
```
=> Don't attempt to parse workflow if it doesn't exist

alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt
*Issue #1183 *
*There was a specific log that keeps on appearing quite frequently on all OpenSearch clusters (even fresh installations). 
`[INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [my-node-name] Detected cluster change event for destination migration`* 
*CheckList:*
=> Removed log entry regarding destination migration

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt
When calling the transport action from another plugin with a separate classloader, the casting will fail and it will hit `recreateObject` fn to perform serialization/deserialization of the request. During deserialization, without converting the `StreamInput` to `NamedWriteableAwareStreamInput`, this was causing failures. This PR adds the `NamedWriteableRegistry` as part of the transport action constructor and in `execute()` in order to resolve this.
Stack trace seen (example coming from `skills` plugin which is calling this transport action via `common-utils` `AlertingPluginInterface.searchMonitors()`:
```
»  java.lang.UnsupportedOperationException: can't read named writeable from StreamInput
»       at org.opensearch.core.common.io.stream.StreamInput.readNamedWri …
```
=> Inject namedWriteableRegistry during ser/deser of SearchMonitorAction

.github/workflows/security-test-workflow.yml, DEVELOPER_GUIDE.md
*Issue #, if available:* #1347
*Description of changes:* removed usages of default password "admin" in admin credentials in security test workflows and relevant documentation
*CheckList:*
- [Y] Commits are signed per the DCO using --signoff
=> removed default admin credentials for alerting

build.gradle
Bumps the ktlint dependency versions to fix a CVE
*CheckList:*
=> Fix CVE-2023-6378

release-notes/opensearch-alerting.release-notes-2.12.0.0.md
Adds release notes for 2.12
*CheckList:*
=> Add 2.12 release notes

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesRequest.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesResponse.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/ClusterMetricsTriggerRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/QueryLevelTriggerRunResult.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/CrossClusterMonitorUtils.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/WriteableTests.kt
Manual backport of PR https://github.com/opensearch-project/alerting/pull/1404
*CheckList:*
=> [Backport 2.x] Implemented cross-cluster monitor support (#1404)

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json
With these changes the number of docs submitted in a single percolate query is not naively set per shard or per index. Rather we have 2 settings to decide how many docs to submit for percolate query in doc level monitor
**Solves the followping problems**
```
IllegalStateException[Failed to run percolate search for sourceIndex [cloudtrail_alias] and queryIndex [.opensearch-sap-cloudtrail-detectors-queries-000001] for 180000 document(s)];
nested: SearchPhaseExecutionException[SearchTask was cancelled]; 
nested: TaskCancelledException[org.opensearch.core.concurrency.OpenSearchRejectedExecutionException: cancelled task with reason: Cancellation timeout of 5m is expired]; 
nested: OpenSearchRejectedExecutionException[cancelled task with reason: Cancellation timeout of 5m is expired];
```
``` …
```
=> Add jvm aware setting and max num docs settings for batching docs for percolate queries

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
#1367
optimize to fetch only fields relevant to doc level queries in doc level monitor instead of entire _source for each doc 
**Percolate query latency BEFORE change: ~10 seconds
Percolate query latency AFTER change: ~1 second**
*CheckList:*
=> optimize to fetch only fields relevant to doc level queries in doc level monitor instead of entire _source for each doc

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
#1296 
When a doc level monitor gets created from the UI every time a character is inputted in the query's value field, the front end sends an execute monitor call to the back end because of the alerting preview query functionality. It performs a monitor dry run at every key press. The queries are then indexed into the query index for the dry run but is not cleaned up afterwards. 
This PR cleans up any monitors with an empty monitor_id `""` i.e. the doc level queries created from a dry run.
*CheckList:* …
=> Clean up doc level queries on dry run

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
[#854](https://github.com/opensearch-project/security-analytics/issues/854)
Related to https://github.com/opensearch-project/security-analytics/pull/852
Checks if `_exists_` is present in the query. If it is, then replace the value with the field name and the correctly appended index name and monitor id.
*CheckList:*
=> Add an _exists_ check to document level monitor queries

alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Manual backport of #1425 to 2.x
---------
*CheckList:*
=> [Backport 2.x] Add an _exists_ check to document level monitor queries (#1425)

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt
*#795*
*Added detectionType severity and searchString as params in Findings API*
*CheckList:*
=> Feature findings enhancemnt

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/service/DeleteMonitorService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/lock/LockModel.kt, core/src/main/kotlin/org/opensearch/alerting/core/lock/LockService.kt, core/src/main/resources/mappings/opensearch-alerting-config-lock.json
add distributed locking to jobs in alerting
*CheckList:*
=> add distributed locking to jobs in alerting

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
This is to modify the findings API enhancements done as part of [issue](https://github.com/opensearch-project/security-analytics/issues/795). The pr contains:
* Moving the query building  part to [SA](https://github.com/opensearch-project/security-analytics/pull/914/files), alerting will use queryBuilder as request param in [GetFindingsRequest](https://github.com/opensearch-project/common-utils/pull/611) to serve the purpose of querying on `.opensearch-sap-*-findings` index to generate findings.
* This PR also includes a flaky integ test for `DocumentMonitorRunnerIT`
*CheckList:*
For more information on following Developer Certificate of Origin and signing off your commits, …
=>  Findings API Enhancements changes and integ tests fix

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/FindingsRestApiIT.kt
*Issue #, if available:* https://github.com/opensearch-project/security-analytics/issues/718
Manually resolves backport of #1325 
*CheckList:*
=> Backport 1325 to 2.5

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
* solution to fix integ tests
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix flaky DocumentMonitor Runner tests
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix findings API enhancemnts
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
(cherry picked from commit ba84d04d56fcbd8eb1ae0c9c35cb9fb6b432afbc)
*CheckList:*
=>  Findings API Enhancements changes and integ tests fix (#1464)

alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/AlertContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/BucketLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AggregationQueryRewriter.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/model/AlertContextTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/util/AlertingUtilsTests.kt
Manual backport of PR https://github.com/opensearch-project/alerting/pull/1450
*CheckList:*
=> [Backport 2.11] Enhance per bucket, and per document monitor notification message ctx. (#1450)

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt
*Track_total_hits to true *
* This PR intends to get total_count of findings if they are more than 10,000 by introducing  `track_total_hits: true` i.e if findings are more than 10,000 it will fetch the actual count. For [ref](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-your-data.html#track-total-hits)
*CheckList:*
=> adding tracking_total_hits in search query for findings

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, release-notes/opensearch-alerting.release-notes-2.13.0.0.md
*[Bug fix](https://github.com/opensearch-project/alerting/pull/1487) and release notes update
*CheckList:*
=> Bug fix and Release notes update

alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertServiceTests.kt
Backport PR https://github.com/opensearch-project/alerting/issues/827
*CheckList:*
=> Backport PR 1366

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
*#825*
*Resurface actual field limit error in DocLevelMonitorRunner when updating index Mappings*
*CheckList:*
=> fix fieldLimit exception in  docLevelMonitor

core/build.gradle
Updates cron-utils (which in turn replaces the deprecatd javax.el 3.0.0 with jakarta.el 3.0.4) to fix the CVE
- sonatype-2020-1438 - https://security.snyk.io/vuln/SNYK-JAVA-ORGGLASSFISH-2841368
*CheckList:*
=> Update cron-utils to fix CVE sonatype-2020-1438

alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
PR related to: https://github.com/opensearch-project/common-utils/pull/630
CI's will fail until common utils PR is merged in
Adds validation check for doc level query name during monitor creation. Doc level query is restricted so that it may not start with: `[_, +, -]`, contain `..`, or contain: `[* ? < > | #]`
*CheckList:*
=> Add validation check for doc level query name during monitor creation

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesRequest.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesResponse.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesHelpers.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetRemoteIndexesActionTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
1. Added input validation for GetRemoteIndexes API, and added related unit and integration tests.
2. Fixed issue where InputService wouldn't wait for cluster metrics monitor to finish executing against all clusters.
https://github.com/opensearch-project/common-utils/pull/633
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/933
*CheckList:*
=> Added input validation, and fixed bug for cross cluster monitors.

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesRequest.kt, alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesResponse.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetRemoteIndexesAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesHelpers.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/action/GetRemoteIndexesActionTests.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Manual backport of PR #1510 
*CheckList:*
=> [Backport 2.x] Added input validation, and fixed bug for cross cluster monitors. (#1510)

alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Adjusted integ tests for when security is enabled.
*CheckList:*
=> Adjusted integ tests for when security is enabled.

.github/workflows/maven-publish.yml
Adjusted maven publish workflow to execute automatically when merging a PR.
*CheckList:*
=> Adjusted maven publish workflow to execute automatically when merging a PR.

alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt, alerting/src/test/kotlin/org/opensearch/alerting/ADTestHelpers.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
Fixed monitor type checks following changes in PR https://github.com/opensearch-project/common-utils/pull/661
*CheckList:*
=> Fixed monitor type checks.

.github/workflows/maven-publish.yml, spi/build.gradle
#1546 
enable publishing of alerting-spi jar
*CheckList:*
=> enable publishing of alerting-spi jar

alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/main/kotlin/org/opensearch/alerting/remote/monitors/RemoteDocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/monitor/fanouts/TransportRemoteDocLevelMonitorFanOutAction.java, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/monitor/inputs/SampleRemoteDocLevelMonitorInput.java, sample-remote-monitor-plugin/src/test/java/org/opensearch/alerting/SampleRemoteMonitorIT.java
#1546 
add support for RemoteDocLevelMonitorInput
*CheckList:*
=> add support for RemoteDocLevelMonitorInput

sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/monitor/fanouts/TransportRemoteDocLevelMonitorFanOutAction.java, sample-remote-monitor-plugin/src/test/java/org/opensearch/alerting/SampleRemoteMonitorIT.java
#1546 
update test case to verify custom triggers work with remote doc-level monitors
*CheckList:*
=> update test case to verify custom triggers work with remote doc-level monitors

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/comments/CommentsIndices.kt, alerting/src/main/kotlin/org/opensearch/alerting/model/AlertContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestDeleteAlertingCommentAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexAlertingCommentAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchAlertingCommentAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/BucketLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/QueryLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteAlertingCommentAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexAlertingCommentAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchAlertingCommentAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/CommentsUtils.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt, alerting/src/main/resources/org/opensearch/alerting/comments/alerting_comments.json, alerting/src/main/resources/org/opensearch/alerting/org.opensearch.alerting.txt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/alerts/NotesIndicesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/AlertingCommentsRestApiIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureAlertingNotesRestApiIT.kt, release-notes/opensearch-alerting.release-notes-2.15.0.0.md
* initial commit, functional but needs refactoring
* refactored QueryLevelTriggerExecutionContext to not need both Alert and AlertContext field, but only AlertContext field
* misc additions and fixes
* misc cleanup
* misc changes and basic ITs
* cleanup
* renaming notes to comments
* misc changes
* changed API endpoints
* more misc changes and fixes
* misc cleanup
* updated a comment
* misc cleanup and setting refresh policy to immediate
* fixed lint issues and other restructuring
* review-based changes
* update after adding entityType to Comment model
* misc fixes
* removing comments history enabled setting
* adding release notes
* IT fixes
* removing dev code vestiges
* changing logger calls
---------
*CheckList:*
By submitting this …
=> [Backport 2.x] Alerting Enhancements: Alerting Comments (Experimental) (#1561)

alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/script/QueryLevelTriggerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt, alerting/src/main/resources/org/opensearch/alerting/org.opensearch.alerting.txt
A follow-up PR to this main PR #1561 for Alerting Comments to address IT failures.
Changed the name of the AlertContext field in QueryLevelTriggerExecutionContext from `alertContext` to `alert`.
*CheckList:*
=> changed alertContext field name to alert

alerting/src/main/kotlin/org/opensearch/alerting/remote/monitors/RemoteDocumentLevelMonitorRunner.kt, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/monitor/fanouts/TransportRemoteDocLevelMonitorFanOutAction.java, sample-remote-monitor-plugin/src/test/java/org/opensearch/alerting/SampleRemoteMonitorIT.java
#1546 
add support for dynamic monitor metadata updates in remote monitors
*CheckList:*
=> add support for dynamic monitor metadata updates in remote monitors

alerting/src/main/kotlin/org/opensearch/alerting/remote/monitors/RemoteDocumentLevelMonitorRunner.kt, sample-remote-monitor-plugin/build.gradle, spi/src/main/kotlin/org/opensearch/alerting/spi/RemoteMonitorRunner.kt
#1546 
fix multi-node test failures
*CheckList:*
=> fix multi-node test failures

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
This PR registers the system indices in this plugin through the SystemIndexPlugin extension point in core. These indices will not be functionally different than they are today, its just a formal registration as a system index.
Related to: https://github.com/opensearch-project/security/issues/4439
*CheckList:*
=> Register system index descriptors through SystemIndexPlugin.getSystemIndexDescriptors

build.gradle
PR https://github.com/opensearch-project/alerting/pull/1593 accidentally bumped 2.15 branch to v2.16. Fixing that increment.
*CheckList:*
=> Fix branch version.

.github/workflows/multi-node-test-workflow.yml, .github/workflows/test-workflow.yml, settings.gradle
#1599 
Re-enable publishing zip to staging repo.
Solves the problem
```
+ mkdir -p builds/maven/org/opensearch
+ cp -r ./build/local-staging-repo/org/opensearch/. builds/maven/org/opensearch
cp: cannot stat './build/local-staging-repo/org/opensearch/.': No such file or directory
2024-07-02 02:16:38 ERROR    ERROR: Command 'bash /tmp/tmp3bqjkb5d/alerting/scripts/build.sh -v 3.0.0 -p linux -a x64 -s false -o builds' returned non-zero exit status 1.
2024-07-02 02:16:38 ERROR    Error building alerting, retry with: ./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component alerting
```
- Full output
```
bash scripts/build.sh -v 3.0.0 -s true
+ getopts :h:v:q:s:o:p:a: arg
+ case $arg in
+ VERSION=3.0.0
+ getopts :h:v:q:s:o:p:a: arg
+ case …
```
=> fix pluginzippublish issue

scripts/build.sh
#1599
PR #1604 fixes the issue of publishing the zip to maven, but it had a side-effect of also publishing the remote monitor plugin zip to the artifacts folder. This PR fixes this issue, attaching the output of the build.
```
➜  alerting git:(2.15) ✗ ./scripts/build.sh -v 2.15.0 -s true
+ getopts :h:v:q:s:o:p:a: arg
+ case $arg in
+ VERSION=2.15.0
+ getopts :h:v:q:s:o:p:a: arg
+ case $arg in
+ SNAPSHOT=true
+ getopts :h:v:q:s:o:p:a: arg
+ '[' -z 2.15.0 ']'
+ [[ ! -z '' ]]
+ [[ true == \t\r\u\e ]]
+ VERSION=2.15.0-SNAPSHOT
+ '[' -z '' ']'
+ OUTPUT=artifacts
+ ./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=2.15.0-SNAPSHOT -Dbuild.version_qualifier= -Dbuild.snapshot=true
To honour the JVM …
```
=> Fixing build script to only publish alerting zip

alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Enable cross-cluster monitor cluster setting
*CheckList:*
=> Enable cross-cluster monitor cluster setting

alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Reverts opensearch-project/alerting#1624
Reverting we will revert this change separately.
=> Revert "Revert "[Backport 2.15] [Backport] Enable cross-cluster monitor cluster setting #1612""

.github/workflows/security-test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt, core/src/main/kotlin/org/opensearch/alerting/core/lock/LockService.kt
backport of #1623 
*CheckList:*
=> [Backport 2.x] fix monitor renew lock issue

sample-remote-monitor-plugin/build.gradle
https://github.com/opensearch-project/alerting/issues/1617
Disabled non-security tests from executing during security-enabled CI workflows.
*CheckList:*
=> Disabled non-security tests from executing during security-enabled CI workflows.

sample-remote-monitor-plugin/build.gradle, sample-remote-monitor-plugin/src/test/java/org/opensearch/alerting/SampleRemoteMonitorPluginIT.java
#1617 
fix distribution builds
*CheckList:*
=> fix distribution builds

.github/workflows/test-workflow.yml
upload-artifact@v1 and upload-artifact@v2 was deprecated. This pr upgrades the github test workflow `upload-artifact` from @v1 to @v3.
=> Upgrade github workflow upload artifact to v3

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/service/DeleteMonitorService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt, core/src/main/resources/mappings/scheduled-jobs.json, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java
separate doc-level monitor query indices for externally defined monitors
Adds boolean flag in monitor config to `deleteQueryIndexInEveryRun`
=> separate doc-level monitor query indices for externally defined monitors

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
move deletion of query index before its creation.
continuing #1664 
=> move deletion of query index before its creation

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
create query index at the time of monitor creation
continuing #1673 
=> create query index at the time of monitor creation

alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt, spi/src/main/kotlin/org/opensearch/alerting/spi/RemoteMonitorRunner.kt
add logging for remote monitor execution flows
=> add logging for remote monitor execution flows

alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java
delete query index only if put mappings throws an exception
continue from #1674
=> delete query index only if put mappings throws an exception

alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
Enabling alerting comments feature by default
=> Enabling alerting comments feature by defualt

alerting/src/main/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregator.kt
This is to fix the compile issue caused by commit in opensearch core https://github.com/opensearch-project/OpenSearch/commit/242827837e7f22e13c2577fc5a15e0932bb66565#diff-82a53ae6a34c3d0e45623b804d761e1fa077c2cea74c1110d92bc808b7d8c5d2
As per the commit convertToStringFilter filter now accepts two params -> https://github.com/opensearch-project/OpenSearch/blame/1.3/server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java#L625
https://github.com/opensearch-project/alerting/issues/1697 …
=> fix compilation error in 1.3

alerting/src/main/kotlin/org/opensearch/alerting/aggregation/bucketselectorext/BucketSelectorExtAggregator.kt, release-notes/opensearch-alerting.release-notes-1.3.20.0.md
=> Add release notes for 1.3

.github/workflows/auto-release.yml, .github/workflows/bwc-test-workflow.yml, .github/workflows/maven-publish.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, .github/workflows/test-workflow.yml, alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt, alerting/src/main/kotlin/org/opensearch/alerting/WorkflowService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt, alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt, sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java
The PR proposes following changes to optimize execution of workflow consisting of bucket-level followed by match-all doc-level monitors.
- Based on a flag `monitor.shouldCreateSingleAlertForFindings` the doc-level monitor is able to ignore storage of findings and alerts and triggering subsequent `publishFinding` calls. https://github.com/opensearch-project/alerting/pull/1729/files#diff-64dadab7578092d0871a6d87833637fcd3c3e56dae448222ec57476921c9707eR300
- Based on a flag `monitor.shouldCreateSingleAlertForFindings` the doc-level monitor is able to just match the trigger condition and generate a single alert and subsequently trigger notification. https://github.com/opensearch-project/alerting/pull/1729/files#diff-64dadab7578092d0871a6d87833637fcd3c3e56dae448222ec57476921c9707eR366
- This …
=> optimize execution of workflow consisting of bucket-level followed by doc-level monitors

.github/workflows/bwc-test-workflow.yml, DEVELOPER_GUIDE.md
Set alerting plugin 3.0.0 baseline JDK version to JDK-21
Closes https://github.com/opensearch-project/alerting/issues/1565
=> Set alerting plugin 3.0.0 baseline JDK version to JDK-21

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Metadata is not fully cleaned up in the alerting config index when a detector is deleted
=> Delete workflow metadata on deleting a detector

alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Force create last run context in monitor workflow metadata when workflow is re-enabled. Currently, the metadata isnt updated, when workflow is disabled, leading to old findings also getting generated by the detector, when the detector was disabled.
=> Force create last run context in monitor workflow metadata when workflow is re-enabled

alerting/build.gradle, alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
Integrated [Opensearch Remote Metadata SDKClient](https://github.com/opensearch-project/opensearch-remote-metadata-sdk) with Alerting
- Added Alerting settings for remote metadata client
- Wired up remote metadata client with alerting
- Onboarded the Remote Metadata Client into `TransportIndexMonitorAction`
Resolves #1821 
=> Integrated OpenSearch Remote Metadata SDKClient with Alerting

alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt, alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt, alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt, alerting/src/main/kotlin/org/opensearch/alerting/listener/PrioritizedActionListener.kt, alerting/src/main/kotlin/org/opensearch/alerting/listener/TimeOutWrappedListener.kt, alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt, alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt, alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
1. Time box doc level monitor execution to 4m
2. Time box doc level monitor execution to 3m
#1853 
=> Timebox doc level monitor execution

alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt
Updating DocLevelFanout action to publish batches of findings instead of individual ones.
https://github.com/opensearch-project/alerting/issues/1859
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented.
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose). …
=> now publishes a list of findings instead of an individual one

.github/workflows/maven-publish.yml, alerting/build.gradle, build-tools/repositories.gradle, build.gradle, sample-remote-monitor-plugin/build.gradle, spi/build.gradle
Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration. 
https://central.sonatype.org/publish/publish-portal-snapshots/
We have stored the `onepassword` token in this repo secrets and new credentials for Sonatypes username & password have been stored in `onepassword`.  These credentials will be exported as env variables which used by maven publish.
Part of a campaign issue https://github.com/opensearch-project/opensearch-build/issues/5551
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificat …
=> Update the maven snapshot publish endpoint and credential

alerting/build.gradle
Pinned the commons-beanutils dependency to 1.11.0 version. 
Fixes the CVE listed at https://advisories.opensearch.org/advisories/CVE-2025-48734
=> Pinned the commons-beanutils dependency to 1.11.0 version

build.gradle
To fix the failure reported here -> https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/10316/pipeline/155
```
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/alerting/3.1.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
at org.gradle.internal.resource.transport.http.HttpClientHelper.processResponse(HttpClientHelper.java:251)
at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:105)
at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:45)
at …
```
=> changed the maven url in build.gradle
